### ISSUE TITLE
split() edge case causes TypeError

### ISSUE THREAD

**Issue by mbway** [Toblerity/Shapely#1002]
## Expected behavior and actual behavior.
The output of this script:
```python
import shapely
from shapely.ops import split
from shapely.geometry import LineString, LinearRing

print(shapely.__version__)
# 1.7.1

b = LineString([(0, 0), (3, 0)])

a = LineString([(1, 1), (1, 0)])
print(split(a, b))
# GEOMETRYCOLLECTION (LINESTRING (1 1, 1 0))

a = LineString([(1, 0), (1, 1), (2, 1), (2, 0)])
print(split(a, b))
# GEOMETRYCOLLECTION (LINESTRING (1 0, 1 1, 2 1, 2 0))

a = LineString([(0, 1), (2, 1), (1, 0), (0, 1)])
print(split(a, b))
# GEOMETRYCOLLECTION (LINESTRING (0 1, 2 1, 1 0), LINESTRING (1 0, 0 1))

a = LineString([(1, 0), (0, 1), (2, 1), (1, 0)])
print(split(a, b))
"""
Traceback (most recent call last):
  File "minimal_example.py", line 23, in <module>
    print(split(a, b))
  File "shapely/ops.py", line 492, in split
    return GeometryCollection(split_func(geom, splitter))
  File "shapely/geometry/collection.py", line 42, in __init__
    self._geom, self._ndim = geos_geometrycollection_from_py(geoms)
  File "shapely/geometry/collection.py", line 59, in geos_geometrycollection_from_py
    L = len(ob)
TypeError: object of type 'LineString' has no len()
"""
```

The output I would have expected from the last split is:
```
GEOMETRYCOLLECTION (LINESTRING (1 0, 0 1, 2 1, 1 0))
```

There are some similarities with this issue and #952 but the cause seems to be different.

## Operating system

Ubuntu 18.04.5

## Shapely version and provenance

1.7.1 from PyPI using pip

**Comment by theroggy** [comment]
Cannot be reproduced anymore, so must have been fixed. Test being added for this situation to avoid regressions.
