### ISSUE TITLE
Broken on macOS 11 with python 3.8.7

### ISSUE THREAD

**Issue by richstokes** [Toblerity/Shapely#1072]
```
Collecting shapely~=1.7
  Using cached Shapely-1.7.1.tar.gz (383 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/rich/.pyenv/versions/3.8.7/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-install-e6zwlin3/shapely/setup.py'"'"'; __file__='"'"'/private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-install-e6zwlin3/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-pip-egg-info-livrvehy
         cwd: /private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-install-e6zwlin3/shapely/
    Complete output (10 lines):
    init_dgelsd failed init
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/36/8b9pzfn56wd_cch3x8zx3l_w0000gn/T/pip-install-e6zwlin3/shapely/setup.py", line 340, in <module>
        import numpy
      File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/numpy/__init__.py", line 286, in <module>
        raise RuntimeError(msg)
    RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
    RankWarning: Polyfit may be poorly conditioned

```

**Comment by Jeremiah-England** [comment]
Hey @richstokes, thanks for the report. To me this looks like #1030.

**Comment by sgillies** [comment]
Yes this is a duplicate.
