### ISSUE TITLE
index out of range for MultiPolygon as wkt

### ISSUE THREAD

**Issue by lays147** [Toblerity/Shapely#1092]
## Expected behavior and actual behavior.

```python
>>> from shapely.geometry import asPoint, asMultiPolygon
>>> data = [[[[30, 20], [45, 40], [10, 40], [30, 20]]]]
>>> mpol = asMultiPolygon(data)
>>> mpol.wkt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lays/fast-ze-challenge/.venv/lib/python3.8/site-packages/shapely/geometry/base.py", line 375, in wkt
    return WKTWriter(lgeos).write(self)
  File "/home/lays/fast-ze-challenge/.venv/lib/python3.8/site-packages/shapely/geos.py", line 397, in write
    if geom is None or geom._geom is None:
  File "/home/lays/fast-ze-challenge/.venv/lib/python3.8/site-packages/shapely/geometry/proxy.py", line 34, in _geom
    self.__geom__, n = self.factory(self.context)
  File "/home/lays/fast-ze-challenge/.venv/lib/python3.8/site-packages/shapely/geometry/multipolygon.py", line 195, in geos_multipolygon_from_polygons
    holes = ob[1]
IndexError: list index out of range
>>> mpol.wkb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lays/fast-ze-challenge/.venv/lib/python3.8/site-packages/shapely/geometry/base.py", line 380, in wkb
    return WKBWriter(lgeos).write(self)
  File "/home/lays/fast-ze-challenge/.venv/lib/python3.8/site-packages/shapely/geos.py", line 521, in write
    if geom is None or geom._geom is None:
  File "/home/lays/fast-ze-challenge/.venv/lib/python3.8/site-packages/shapely/geometry/proxy.py", line 34, in _geom
    self.__geom__, n = self.factory(self.context)
  File "/home/lays/fast-ze-challenge/.venv/lib/python3.8/site-packages/shapely/geometry/multipolygon.py", line 195, in geos_multipolygon_from_polygons
    holes = ob[1]
IndexError: list index out of range
>>> 
```

## Steps to reproduce the problem.
Run script above.

## Operating system

Ubuntu 20.04
Python 3.8.5

## Shapely version and provenance
Shapely 1.7.1 from PyPi using pip

**Comment by lays147** [comment]
If instead of ``asMultiPolygon`` I use ``shape`` it works:
```python
>>> from shapely.geometry import shape
>>> s = shape({
...             "type": "MultiPolygon",
...             "coordinates": [[[[30, 20], [45, 40], [10, 40], [30, 20]]]]
...         })
>>> s
<shapely.geometry.multipolygon.MultiPolygon object at 0x7fe6a67dfd60>
>>> s.wkt
'MULTIPOLYGON (((30 20, 45 40, 10 40, 30 20)))'
>>> 
```

**Comment by jorisvandenbossche** [comment]
I would recommend to use `shape` instead. Note that `asMultiPolygon` does not return an actual geometry object, but a "proxy" object (keeping the data in the dictionary), which will also be deprecated in the next Shapely version (1.8)

**Comment by sgillies** [comment]
We won't be fixing this one in 1.8.x. It won't be a problem in 2.0.
