### ISSUE TITLE
Missing module shapely.vectorized when installing shapely[vectorized] from sources

### ISSUE THREAD

**Issue by remy-phelipot** [Toblerity/Shapely#1127]
## Expected behavior and actual behavior.

Two pre-requisites are needed to generate the [shapely.vectorized](../tree/master/shapely/vectorized) module from sources: `cython` and `numpy`

When a end-user module that uses shapely is installed, the install command should be:

```console 
$ pip install end-user-module --no-binary shapely
```
But issues are occurring on a fresh Python environment when doing so: as Cython and numpy are not pre-installed the vectorized module is not generated, even if the dependency in `end-user-module` is declared like `shapely[vectorized]`.

Main problem is that cython is still a build dependency that cannot be handled correctly by `setuptools`.

## Steps to reproduce the problem.

On a fresh Python environment:

```console
$ pip install shapely[vectorized] --no-binary shapely
$ python3 -c 'import shapely.vectorized'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aaaaa/Documents/Shapely/.venv/lib/python3.8/site-packages/shapely/vectorized/__init__.py", line 3, in <module>
    from ._vectorized import (contains, touches)
ModuleNotFoundError: No module named 'shapely.vectorized._vectorized'
```

## Operating system

Linux 64bits

## Shapely version and provenance

1.7.1

**Comment by remy-phelipot** [comment]
A possible solution to this issue is to add a `pyproject.toml` ([See PEP-517](https://www.python.org/dev/peps/pep-0517/)) file with the following content:

```toml
[build-system]
requires = ["setuptools", "wheel", "cython", "numpy"]
```

In this case, installation have the following results:

```console
$ pip install Shapely/dist/Shapely-1.8a2.tar.gz[vectorized] --no-binary shapely
$ python3 -c 'import shapely.vectorized'
$ echo $?
0
```

```console
$ pip install Shapely/dist/Shapely-1.8a2.tar.gz --no-binary shapely
$ python3 -c 'import shapely.vectorized'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ender/Documents/Shapely/.venv/lib/python3.8/site-packages/shapely/vectorized/__init__.py", line 3, in <module>
    from ._vectorized import (contains, touches)
  File "shapely/vectorized/_vectorized.pyx", line 1, in init shapely.vectorized._vectorized
ModuleNotFoundError: No module named 'numpy'
0
```
