### ISSUE TITLE
Exception ignored in BaseGeometry.__del__, AttributeError: can't set attribute

### ISSUE THREAD

**Issue by mwtoews** [Toblerity/Shapely#1149]
This is an issue with tests with Python 3.8 or later. Tests pass, but show warnings to pytest. Specifically:
```
pytest -v tests/test_geointerface.py::GeoInterfaceTestCase::test_geointerface_adapter
```
with output:
```
tests/test_geointerface.py::GeoInterfaceTestCase::test_geointerface_adapter Exception ignored in: <function BaseGeometry.__del__ at 0x7fbe6c2ffb80>
Traceback (most recent call last):
  File "/data/mtoews/src/shapely/shapely/geometry/base.py", line 208, in __del__
    self._empty(val=None)
  File "/data/mtoews/src/shapely/shapely/geometry/base.py", line 198, in _empty
    self._is_empty = True
AttributeError: can't set attribute
```
And if numpy is installed:
```
pytest -v tests/test_point.py::PointTestCase::test_numpy_adapter
```
with output:
```
tests/test_point.py::PointTestCase::test_numpy_adapter Exception ignored in: <function BaseGeometry.__del__ at 0x7f2b8123ab80>
Traceback (most recent call last):
  File "/data/mtoews/src/shapely/shapely/geometry/base.py", line 208, in __del__
    self._empty(val=None)
  File "/data/mtoews/src/shapely/shapely/geometry/base.py", line 198, in _empty
    self._is_empty = True
AttributeError: can't set attribute
```

**Comment by mwtoews** [comment]
A short method to show this warning is with three lines:
```pycon
>>> from shapely.geometry import asPoint
>>> pa = asPoint([1, 2])
sys:1: ShapelyDeprecationWarning: The proxy geometries (through the 'asShape()', 'asPoint()' or 'PointAdapter()' constructors) are deprecated and will be removed in Shapely 2.0. Use the 'shape()' function or the standard 'Point()' constructor instead.
>>> del pa
Exception ignored in: <function BaseGeometry.__del__ at 0x7f5df65d9a60>
Traceback (most recent call last):
  File "/data/mtoews/src/shapely/shapely/geometry/base.py", line 208, in __del__
    self._empty(val=None)
  File "/data/mtoews/src/shapely/shapely/shapely/geometry/base.py", line 198, in _empty
    self._is_empty = True
AttributeError: can't set attribute
```
----
This issue is related to the "precarious circumstances under which `__del__()` methods are invoked" ([ref](https://docs.python.org/3.8/reference/datamodel.html#object.__del__)). Also, this is an issue with a deprecated feature that shouldn't be in use, so this is a really low priority issue.

**Comment by jorisvandenbossche** [comment]
Since the proxy geometry classes are deprecated in 1.8 anyway, maybe not really needed to fix this in 1.8? (i.e. the milestone can be removed?)
