### ISSUE TITLE
transform(func, GeometryCollection) fails

### ISSUE THREAD

**Issue by Zverik** [Toblerity/Shapely#256]
This code produces an error:
```python
from shapely.wkt import loads
from shapely.ops import transform
coll = loads('GEOMETRYCOLLECTION(POINT(0 0))')
transform(lambda x, y, z=None: (x, y), coll)
```
Stacktrace is:
```
Traceback (most recent call last):
  File "geomcollbug.py", line 5, in <module>
    transform(lambda x, y, z=None: (x, y), coll)
  File "/usr/lib64/python2.7/site-packages/shapely/ops.py", line 206, in transform
    return type(geom)([transform(func, part) for part in geom.geoms])
TypeError: __init__() takes exactly 1 argument (2 given)
```
Reason is: #33
See also: #74

**Comment by Zverik** [comment]
Sorry, I was using 1.2.18, and it's fixed in 1.5.0 (#200).
