### ISSUE TITLE
Speedups not enabled when trying to build on Ubuntu with Python 3.4.3

### ISSUE THREAD

**Issue by MattDMo** [Toblerity/Shapely#318]
I'm trying to build Shapely so I can install Cartopy, part of matplotlib's `mpl_toolkits`. I'm on Ubuntu 15.04 running Python 3.4.3, and have Cython 0.23.1 installed. I downloaded the Shapely v. `1.5.12.tar.gz` file, extracted it, and the following happened:

```
$ python3 setup.py build
Traceback (most recent call last):
  File "Cython/Compiler/Visitor.py", line 173, in Cython.Compiler.Visitor.TreeVisitor._visit (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:4449)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/ParseTreeTransforms.py", line 1911, in visit_FuncDefNode
    node.body = node.body.analyse_expressions(node.local_scope)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Nodes.py", line 430, in analyse_expressions
    for stat in self.stats ]
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Nodes.py", line 430, in <listcomp>
    for stat in self.stats ]
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Nodes.py", line 4775, in analyse_expressions
    node = self.analyse_types(env)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Nodes.py", line 4928, in analyse_types
    rhs = self.rhs.coerce_to(dtype, env)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/ExprNodes.py", line 5791, in coerce_to
    return ExprNode.coerce_to(self, dst_type, env)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/ExprNodes.py", line 811, in coerce_to
    src = CoerceFromPyTypeNode(dst_type, src, env)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/ExprNodes.py", line 11940, in __init__
    if not result_type.create_from_py_utility_code(env):
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/PyrexTypes.py", line 436, in create_from_py_utility_code
    return self.typedef_base_type.create_from_py_utility_code(env)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/PyrexTypes.py", line 1534, in create_from_py_utility_code
    "FROM_PY_FUNCTION": self.from_py_function}))
  File "Cython/Compiler/Code.py", line 279, in Cython.Compiler.Code.UtilityCodeBase.load_cached (/build/buildd/cython-0.21.1/Cython/Compiler/Code.c:8161)
TypeError: load_cached() got an unexpected keyword argument 'context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Cython/Compiler/Visitor.py", line 173, in Cython.Compiler.Visitor.TreeVisitor._visit (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:4440)
  File "Cython/Compiler/Visitor.py", line 289, in Cython.Compiler.Visitor.CythonTransform.visit_Node (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:6594)
  File "Cython/Compiler/Visitor.py", line 241, in Cython.Compiler.Visitor.VisitorTransform.visitchildren (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:5521)
  File "Cython/Compiler/Visitor.py", line 212, in Cython.Compiler.Visitor.TreeVisitor._visitchildren (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:5202)
  File "Cython/Compiler/Visitor.py", line 186, in Cython.Compiler.Visitor.TreeVisitor._visitchild (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:4726)
  File "Cython/Compiler/Visitor.py", line 181, in Cython.Compiler.Visitor.TreeVisitor._visit (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:4616)
  File "Cython/Compiler/Visitor.py", line 140, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:3754)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 114, in __init__
    CompileError.__init__(self, pos, message)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 60, in __init__
    self.formatted_message = format_error(message, position)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 51, in format_error
    cont = context(position)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 32, in context
    F = source.get_lines()
  File "Cython/Compiler/Scanning.py", line 195, in Cython.Compiler.Scanning.FileSourceDescriptor.get_lines (/build/buildd/cython-0.21.1/Cython/Compiler/Scanning.c:5342)
TypeError: open_source_file() got an unexpected keyword argument 'require_normalised_newlines'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Cython/Compiler/Visitor.py", line 173, in Cython.Compiler.Visitor.TreeVisitor._visit (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:4440)
  File "Cython/Compiler/Visitor.py", line 289, in Cython.Compiler.Visitor.CythonTransform.visit_Node (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:6594)
  File "Cython/Compiler/Visitor.py", line 241, in Cython.Compiler.Visitor.VisitorTransform.visitchildren (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:5521)
  File "Cython/Compiler/Visitor.py", line 212, in Cython.Compiler.Visitor.TreeVisitor._visitchildren (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:5202)
  File "Cython/Compiler/Visitor.py", line 186, in Cython.Compiler.Visitor.TreeVisitor._visitchild (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:4726)
  File "Cython/Compiler/Visitor.py", line 181, in Cython.Compiler.Visitor.TreeVisitor._visit (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:4616)
  File "Cython/Compiler/Visitor.py", line 140, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:3754)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 114, in __init__
    CompileError.__init__(self, pos, message)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 60, in __init__
    self.formatted_message = format_error(message, position)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 51, in format_error
    cont = context(position)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 32, in context
    F = source.get_lines()
  File "Cython/Compiler/Scanning.py", line 195, in Cython.Compiler.Scanning.FileSourceDescriptor.get_lines (/build/buildd/cython-0.21.1/Cython/Compiler/Scanning.c:5342)
TypeError: open_source_file() got an unexpected keyword argument 'require_normalised_newlines'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Cython/Compiler/Visitor.py", line 173, in Cython.Compiler.Visitor.TreeVisitor._visit (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:4449)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/ParseTreeTransforms.py", line 1906, in visit_ModuleNode
    self.visitchildren(node)
  File "Cython/Compiler/Visitor.py", line 240, in Cython.Compiler.Visitor.VisitorTransform.visitchildren (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:5826)
  File "Cython/Compiler/Visitor.py", line 241, in Cython.Compiler.Visitor.VisitorTransform.visitchildren (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:5521)
  File "Cython/Compiler/Visitor.py", line 214, in Cython.Compiler.Visitor.TreeVisitor._visitchildren (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:5222)
  File "Cython/Compiler/Visitor.py", line 186, in Cython.Compiler.Visitor.TreeVisitor._visitchild (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:4726)
  File "Cython/Compiler/Visitor.py", line 181, in Cython.Compiler.Visitor.TreeVisitor._visit (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:4616)
  File "Cython/Compiler/Visitor.py", line 140, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:3754)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 114, in __init__
    CompileError.__init__(self, pos, message)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 60, in __init__
    self.formatted_message = format_error(message, position)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 51, in format_error
    cont = context(position)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 32, in context
    F = source.get_lines()
  File "Cython/Compiler/Scanning.py", line 195, in Cython.Compiler.Scanning.FileSourceDescriptor.get_lines (/build/buildd/cython-0.21.1/Cython/Compiler/Scanning.c:5342)
TypeError: open_source_file() got an unexpected keyword argument 'require_normalised_newlines'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cython", line 11, in <module>
    sys.exit(setuptools_main())
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Main.py", line 687, in setuptools_main
    return main(command_line = 1)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Main.py", line 704, in main
    result = compile(sources, options)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Main.py", line 679, in compile
    return compile_multiple(source, options)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Main.py", line 657, in compile_multiple
    result = run_pipeline(source, options, context=context)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Main.py", line 487, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Pipeline.py", line 328, in run_pipeline
    data = phase(data)
  File "Cython/Compiler/Visitor.py", line 279, in Cython.Compiler.Visitor.CythonTransform.__call__ (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:6402)
  File "Cython/Compiler/Visitor.py", line 262, in Cython.Compiler.Visitor.VisitorTransform.__call__ (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:6068)
  File "Cython/Compiler/Visitor.py", line 181, in Cython.Compiler.Visitor.TreeVisitor._visit (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:4616)
  File "Cython/Compiler/Visitor.py", line 140, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error (/build/buildd/cython-0.21.1/Cython/Compiler/Visitor.c:3754)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 114, in __init__
    CompileError.__init__(self, pos, message)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 60, in __init__
    self.formatted_message = format_error(message, position)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 51, in format_error
    cont = context(position)
  File "/usr/local/lib/python3.4/dist-packages/Cython/Compiler/Errors.py", line 32, in context
    F = source.get_lines()
  File "Cython/Compiler/Scanning.py", line 195, in Cython.Compiler.Scanning.FileSourceDescriptor.get_lines (/build/buildd/cython-0.21.1/Cython/Compiler/Scanning.c:5342)
TypeError: open_source_file() got an unexpected keyword argument 'require_normalised_newlines'
WARNING:setup.py:Could not (re)create C extension with Cython.
WARNING:setup.py:speedup extension not found
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.4
creating build/lib.linux-x86_64-3.4/shapely
copying shapely/validation.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/prepared.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/topology.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/linref.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/wkt.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/libgeos.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/__init__.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/affinity.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/coords.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/ftools.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/geos.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/predicates.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/strtree.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/ops.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/iterops.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/wkb.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/impl.py -> build/lib.linux-x86_64-3.4/shapely
copying shapely/ctypes_declarations.py -> build/lib.linux-x86_64-3.4/shapely
creating build/lib.linux-x86_64-3.4/shapely/geometry
copying shapely/geometry/linestring.py -> build/lib.linux-x86_64-3.4/shapely/geometry
copying shapely/geometry/proxy.py -> build/lib.linux-x86_64-3.4/shapely/geometry
copying shapely/geometry/multilinestring.py -> build/lib.linux-x86_64-3.4/shapely/geometry
copying shapely/geometry/__init__.py -> build/lib.linux-x86_64-3.4/shapely/geometry
copying shapely/geometry/point.py -> build/lib.linux-x86_64-3.4/shapely/geometry
copying shapely/geometry/geo.py -> build/lib.linux-x86_64-3.4/shapely/geometry
copying shapely/geometry/polygon.py -> build/lib.linux-x86_64-3.4/shapely/geometry
copying shapely/geometry/multipoint.py -> build/lib.linux-x86_64-3.4/shapely/geometry
copying shapely/geometry/base.py -> build/lib.linux-x86_64-3.4/shapely/geometry
copying shapely/geometry/multipolygon.py -> build/lib.linux-x86_64-3.4/shapely/geometry
copying shapely/geometry/collection.py -> build/lib.linux-x86_64-3.4/shapely/geometry
creating build/lib.linux-x86_64-3.4/shapely/algorithms
copying shapely/algorithms/__init__.py -> build/lib.linux-x86_64-3.4/shapely/algorithms
copying shapely/algorithms/cga.py -> build/lib.linux-x86_64-3.4/shapely/algorithms
creating build/lib.linux-x86_64-3.4/shapely/examples
copying shapely/examples/__init__.py -> build/lib.linux-x86_64-3.4/shapely/examples
copying shapely/examples/dissolve.py -> build/lib.linux-x86_64-3.4/shapely/examples
copying shapely/examples/geoms.py -> build/lib.linux-x86_64-3.4/shapely/examples
copying shapely/examples/intersect.py -> build/lib.linux-x86_64-3.4/shapely/examples
creating build/lib.linux-x86_64-3.4/shapely/speedups
copying shapely/speedups/__init__.py -> build/lib.linux-x86_64-3.4/shapely/speedups
creating build/lib.linux-x86_64-3.4/shapely/vectorized
copying shapely/vectorized/__init__.py -> build/lib.linux-x86_64-3.4/shapely/vectorized
running build_ext
building 'shapely.speedups._speedups' extension
creating build/temp.linux-x86_64-3.4
creating build/temp.linux-x86_64-3.4/shapely
creating build/temp.linux-x86_64-3.4/shapely/speedups
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c shapely/speedups/_speedups.c -o build/temp.linux-x86_64-3.4/shapely/speedups/_speedups.o
x86_64-linux-gnu-gcc: error: shapely/speedups/_speedups.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
WARNING:setup.py:command 'x86_64-linux-gnu-gcc' failed with exit status 4
WARNING:setup.py:The C extension could not be compiled, speedups are not enabled.
WARNING:setup.py:Failure information, if any, is above.
WARNING:setup.py:I'm retrying the build without the C extension now.
running build
running build_py
creating build/lib
creating build/lib/shapely
copying shapely/validation.py -> build/lib/shapely
copying shapely/prepared.py -> build/lib/shapely
copying shapely/topology.py -> build/lib/shapely
copying shapely/linref.py -> build/lib/shapely
copying shapely/wkt.py -> build/lib/shapely
copying shapely/libgeos.py -> build/lib/shapely
copying shapely/__init__.py -> build/lib/shapely
copying shapely/affinity.py -> build/lib/shapely
copying shapely/coords.py -> build/lib/shapely
copying shapely/ftools.py -> build/lib/shapely
copying shapely/geos.py -> build/lib/shapely
copying shapely/predicates.py -> build/lib/shapely
copying shapely/strtree.py -> build/lib/shapely
copying shapely/ops.py -> build/lib/shapely
copying shapely/iterops.py -> build/lib/shapely
copying shapely/wkb.py -> build/lib/shapely
copying shapely/impl.py -> build/lib/shapely
copying shapely/ctypes_declarations.py -> build/lib/shapely
creating build/lib/shapely/geometry
copying shapely/geometry/linestring.py -> build/lib/shapely/geometry
copying shapely/geometry/proxy.py -> build/lib/shapely/geometry
copying shapely/geometry/multilinestring.py -> build/lib/shapely/geometry
copying shapely/geometry/__init__.py -> build/lib/shapely/geometry
copying shapely/geometry/point.py -> build/lib/shapely/geometry
copying shapely/geometry/geo.py -> build/lib/shapely/geometry
copying shapely/geometry/polygon.py -> build/lib/shapely/geometry
copying shapely/geometry/multipoint.py -> build/lib/shapely/geometry
copying shapely/geometry/base.py -> build/lib/shapely/geometry
copying shapely/geometry/multipolygon.py -> build/lib/shapely/geometry
copying shapely/geometry/collection.py -> build/lib/shapely/geometry
creating build/lib/shapely/algorithms
copying shapely/algorithms/__init__.py -> build/lib/shapely/algorithms
copying shapely/algorithms/cga.py -> build/lib/shapely/algorithms
creating build/lib/shapely/examples
copying shapely/examples/__init__.py -> build/lib/shapely/examples
copying shapely/examples/dissolve.py -> build/lib/shapely/examples
copying shapely/examples/geoms.py -> build/lib/shapely/examples
copying shapely/examples/intersect.py -> build/lib/shapely/examples
creating build/lib/shapely/speedups
copying shapely/speedups/__init__.py -> build/lib/shapely/speedups
creating build/lib/shapely/vectorized
copying shapely/vectorized/__init__.py -> build/lib/shapely/vectorized
WARNING:setup.py:The C extension could not be compiled, speedups are not enabled.
```

`setuptools` is up to date, according to `pip`, I have `libgeos` 3.4.2 installed through Ubuntu's package manager, and I can't think of anything else I need. Any ideas?

**Comment by sgillies** [comment]
While you're expecting to be using Cython 0.23, the build log is full of references to `/build/buildd/cython-0.21.1`. My hunch is that once you resolve this you'll be on your way.

**Comment by MattDMo** [comment]
@sgillies Weird. All I had in `/usr/local/lib/python3.4/dist-packages` for Cython was:

```
drwxr-sr-x  13 root    4096 Aug 24 21:10 Cython/
drwxr-sr-x   2 root    4096 Aug 24 21:10 Cython-0.23.1.dist-info/
-rw-r--r--   1 root     520 Aug 24 21:10 cython.py
```
I deleted it all and reinstalled with `pip`, then reran the Shapely build, and aside from a few `-Wmaybe-uninitialized` complaints and the like, it built and installed fine. I guess this is what happens when you have both Ubuntu and `pip` trying to manage package versions. Anyway, thanks for the pointer!
