### ISSUE TITLE
Shapely install fails on Ubuntu 12.04.5

### ISSUE THREAD

**Issue by iandees** [Toblerity/Shapely#321]
In the `pip install` for https://github.com/hotosm/osm-tasking-manager2 on Ubuntu 12.04.5, I get:

```
Downloading/unpacking shapely (from osmtm==2.12-dev->-r requirements.txt (line 1))
  Running setup.py egg_info for package shapely
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/build/shapely/setup.py", line 38, in <module>
        from shapely.libgeos import geos_version_string, geos_version, \
      File "shapely/libgeos.py", line 83, in <module>
        clibs = get_geos_config('--clibs')
      File "shapely/libgeos.py", line 72, in get_geos_config
        raise ValueError(stderr.strip())
    ValueError: Usage: geos-config [OPTIONS]
    Options:
         [--prefix]
         [--version]
         [--libs]
         [--cflags]
         [--ldflags]
         [--includes]
         [--jtsport]
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/build/shapely/setup.py", line 38, in <module>

    from shapely.libgeos import geos_version_string, geos_version, \

  File "shapely/libgeos.py", line 83, in <module>

    clibs = get_geos_config('--clibs')

  File "shapely/libgeos.py", line 72, in get_geos_config

    raise ValueError(stderr.strip())

ValueError: Usage: geos-config [OPTIONS]

Options:

     [--prefix]

     [--version]

     [--libs]

     [--cflags]

     [--ldflags]

     [--includes]

     [--jtsport]

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/build/shapely
Storing complete log in /home/iandees/.pip/pip.log
```

`geos-config` exists and is version 3.2.2:

```bash
$ geos-config --version --help
3.2.2
Usage: geos-config [OPTIONS]
Options:
     [--prefix]
     [--version]
     [--libs]
     [--cflags]
     [--ldflags]
     [--includes]
     [--jtsport]
```

**Comment by iandees** [comment]
Ah, sorry. I skipped over the bit in the readme that says geos >= 3.3.

**Comment by iandees** [comment]
(Just to be more explicit to people finding this via Google: you need to figure out how to install geos >= 3.3.2 on your machine before Shapely will install)

**Comment by sgillies** [comment]
@iandees I'm glad you got this sorted. The ubuntugis PPA is the place to get GEOS 3.4.2 (PPA is even included by default on Travis's linux container infrastructure).
