### ISSUE TITLE
Python 3: wkb.loads(g, hex=True) `AttributeError` (.encode)

### ISSUE THREAD

**Issue by brendancol** [Toblerity/Shapely#362]
The example below works fine in python 2.7, but breaks in 3.5.

reproduction:
```python
from __future__ import print_function
from shapely import wkb

geom = b'0103000000010000007F00000070F584C3FB7058C0D7B0F8BB3F3E3E4070F584C3FB7058C06714E139D9433E401A12F758FA7058C09426A5A0DB433E40F8A3A833F77058C08D9944BDE0433E402E19C748F67058C021AF0793E2433E4082A7902BF57058C0256C3F19E3433E40170B43E4F47058C00F10CCD1E3433E403424EEB1F47058C0188A3BDEE4433E40E3175E49F27058C052EC681CEA433E40253B3602F17058C087F9F202EC433E406D35EB8CEF7058C0D81F28B7ED433E4080D4264EEE7058C00E2DB29DEF433E4045F0BF95EC7058C0D092C7D3F2433E40F786C267EB7058C04C4C1762F5433E40B2F4A10BEA7058C0DBA4A2B1F6433E40E869C020E97058C032880FECF8433E402504ABEAE57058C0C4CDA96400443E408B4B55DAE27058C02C80290307443E40390B7BDAE17058C071C45A7C0A443E404016A243E07058C0B7088CF50D443E40C328081EDF7058C0047289230F443E40895E46B1DC7058C02A357BA015443E40181F662FDB7058C06BBC749318443E40A1224E27D97058C0C0374D9F1D443E408B14CAC2D77058C01ED8F15F20443E408C2E6F0ED77058C0CB49287D21443E4087A5811FD57058C07C78962023443E4003E10A28D47058C08DAF3DB324443E404147AB5AD27058C03E76172829443E406451D845D17058C0919C4CDC2A443E40EF3A1BF2CF7058C060E4654D2C443E409D4830D5CC7058C0DFF2583332443E40EBFF1CE6CB7058C01ABD1AA034443E40FEB8FDF2C97058C005B64AB038443E408D791D71C87058C0816F9A3E3B443E40B75A272EC77058C0C1F693313E443E40E8465854C47058C0A10DC00644443E406D8D08C6C17058C0C3137AFD49443E4065FD6662BA7058C02AE3DF675C443E403849F3C7B47058C06F44F7AC6B443E404D9EB29AAE7058C067D47C957C443E409B1E1494A27058C011A452EC68443E40742497FF907058C0BBEEAD484C443E403502F1BA7E7058C03C0E83F92B443E40D4D51D8B6D7058C01324B6BB07443E40CD328B506C7058C0F7729F1C05443E40F23CB83B6B7058C0FD976BD102443E402713B70A627058C04EB4AB90F2433E40C1E270E6577058C0BA8102EFE4433E4013D21A834E7058C0A208A9DBD9433E40B08EE3874A7058C07ADD2230D6433E40B67F65A5497058C0F141CF66D5433E40797AA52C437058C02F444E5FCF433E40BC395CAB3D7058C0DAC87553CA433E4007CDAE7B2B7058C070917BBABA433E40895A9A5B217058C0A10F96B1A1433E40B9F8DB9E207058C00DFAD2DB9F433E4099F221A81A7058C0DE24068195433E40AAF23D23117058C0F5FBFECD8B433E408597E0D4077058C0CA4BFE277F433E40EF30ED9BFB6F58C0D99596917A433E40C362D4B5F66F58C06669A7E672433E40F9D4B14AE96F58C00A7C45B75E433E40334E4354E16F58C023BBD23252433E408EE733A0DE6F58C0F4D214014E433E40122EE411DC6F58C04BC972124A433E400DD940BAD86F58C09445611745433E408F183DB7D06F58C031CB9E0436433E40486C770FD06F58C0809C306134433E40C3BAF1EEC86F58C0E257ACE122433E405F43705CC66F58C03291D26C1E433E40C66D3480B76F58C0905F3FC406433E4015A75A0BB36F58C0C02A172AFF423E40FEB27BF2B06F58C036F7578FFB423E4005BEA25BAF6F58C07A4E7ADFF8423E4054C37E4FAC6F58C040EC4CA1F3423E4089997D1EA36F58C011FA997ADD423E4060200890A16F58C048D74CBED9423E407B80EECB996F58C0DD1AD82AC1423E401DACFF73986F58C0103B53E8BC423E40C8B260E28F6F58C05790662C9A423E40B340BB438A6F58C0B471C45A7C423E40A20914B1886F58C05C09DD2571423E405CC5E237856F58C06D6E4C4F58423E4011DE1E84806F58C0619D2ADF33423E401EC022BF7E6F58C09AA8A5B915423E400798F90E7E6F58C0D725AAB706423E402BA226FA7C6F58C097FC4FFEEE413E401494A2957B6F58C015C78157CB413E40E5F21FD26F6F58C0D70A9A9658413E402E3BC43F6C6F58C0C9694FC939413E405E5B3FFD676F58C07C5EF1D423413E40EF694E5E646F58C0F775E09C11413E4074B0FECF616F58C04AE7C3B304413E409E2633DE566F58C0D576137CD3403E40FE7C5BB0546F58C073E95F92CA403E40242367614F6F58C007C556D0B4403E40E8B985AE446F58C01D75745C8D403E406038D730436F58C00851BEA085403E401BF4A5B73F6F58C039ECBE6378403E4000DF6DDE386F58C01A31B3CF63403E409BE271512D6F58C0CB2555DB4D403E40B6F468AA276F58C00DF8FC3042403E40191BBAD91F6F58C03FFB912232403E40D288997D1E6F58C0A62897C62F403E40FC69A33A1D6F58C0887780272D403E407BBFD18E1B6F58C0670932022A403E40570394861A6F58C09204E10A28403E401C058882196F58C02378431A15403E40596B28B5176F58C0173F8D7BF33F3E40A07F828B156F58C0A353573ECB3F3E40BAF59A1E146F58C0048A58C4B03F3E40E50AEF72116F58C001C11C3D7E3F3E4080457EFD106F58C023128596753F3E404B1E4FCB0F6F58C02FBABC395C3F3E40C29CA04D0E6F58C0DC6CACC43C3F3E40345EBA490C6F58C0AF95D05D123F3E403C69E1B20A6F58C0E34BA8E0F03E3E40E23785950A6F58C05721E527D53E3E406416A1D80A6F58C061DC0DA2B53E3E40A0FA07910C6F58C03EAF78EA913E3E408D4127840E6F58C0738236397C3E3E40446117450F6F58C017B2BAD5733E3E4061122EE4116F58C001840F255A3E3E401FBB0B94146F58C0E9EDCF45433E3E40B416F71D156F58C0D7B0F8BB3F3E3E4070F584C3FB7058C0D7B0F8BB3F3E3E40'

shp = wkb.loads(geom, hex=True)
print(shp)
```

### Python 2.7
```python
POLYGON ((-97.76536643966915 30.24316000768235, -97.76536643966915 30.26503335709677, -97.76527999999999 30.26506999999999, -97.76508799999999 30.265148, -97.76503199999999 30.265176, -97.76496399999999 30.26518399999999, -97.76494699999999 30.265195, -97.76493499999998 30.26521099999999, -97.764788 30.265291, -97.76470999999999 30.26532, -97.76462099999999 30.26534599999999, -97.764545 30.265375, -97.76443999999999 30.265424, -97.76436799999998 30.265463, -97.764285 30.265483, -97.764229 30.265517, -97.764033 30.265631, -97.76384599999999 30.265732, -97.763785 30.265785, -97.763688 30.265838, -97.76361799999999 30.265856, -97.76347 30.265955, -97.76337799999999 30.266, -97.76325399999998 30.266077, -97.76316899999999 30.266119, -97.763126 30.266136, -97.763008 30.266161, -97.76294899999998 30.266185, -97.762839 30.266253, -97.76277299999998 30.266279, -97.762692 30.266301, -97.762502 30.266391, -97.762445 30.266428, -97.762326 30.26648999999999, -97.76223399999999 30.26652899999999, -97.76215699999999 30.26657399999999, -97.76198299999999 30.266663, -97.761827 30.266754, -97.761376 30.267035, -97.761034 30.267268, -97.76065699999999 30.267526, -97.759923 30.267226, -97.75885 30.266789, -97.75773499999998 30.266296, -97.756686 30.265743, -97.75661099999998 30.265703, -97.75654499999999 30.26566799999999, -97.755984 30.26542, -97.755365 30.265212, -97.75479199999999 30.265043, -97.754549 30.264987, -97.75449499999999 30.264975, -97.75410000000001 30.26488299999999, -97.75376399999999 30.264806, -97.75265399999999 30.264568, -97.75203599999999 30.264186, -97.75199099999999 30.264158, -97.751627 30.264, -97.751046 30.263852, -97.750478 30.263659, -97.74973199999998 30.263589, -97.749433 30.263472, -97.74861399999999 30.263164, -97.74812799999999 30.262973, -97.747963 30.26290899999999, -97.74780699999999 30.262849, -97.74760299999998 30.262773, -97.747114 30.262543, -97.747074 30.262518, -97.746639 30.262251, -97.746482 30.262183, -97.745575 30.261822, -97.74530299999999 30.261706, -97.74517499999999 30.26165099999999, -97.74507799999999 30.26161, -97.74489199999999 30.26152999999999, -97.744331 30.261192, -97.744236 30.261135, -97.74376199999999 30.26075999999999, -97.74368 30.260695, -97.743157 30.260165, -97.742814 30.25971, -97.742718 30.259539, -97.74250599999999 30.25916, -97.74221899999999 30.25860399999999, -97.74211099999999 30.25814399999999, -97.742069 30.25791499999999, -97.742003 30.257553, -97.741918 30.257009, -97.74120000000001 30.25525799999999, -97.740982 30.25478799999999, -97.74072199999998 30.254453, -97.74050099999998 30.254175, -97.74034499999999 30.253978, -97.739677 30.253227, -97.739544 30.25309099999999, -97.73921999999999 30.25275899999999, -97.73856699999999 30.252157, -97.73847599999999 30.252039, -97.738264 30.251837, -97.73784599999999 30.251523, -97.73714099999999 30.251188, -97.736796 30.25101, -97.73631899999999 30.250765, -97.73623599999999 30.250729, -97.73615899999999 30.25068899999999, -97.736057 30.250641, -97.73599399999999 30.250611, -97.73593199999999 30.25032199999999, -97.735822 30.249809, -97.73568999999998 30.249195, -97.735603 30.248791, -97.73544 30.24802, -97.735412 30.247888, -97.735339 30.247501, -97.73524799999998 30.247021, -97.73512499999998 30.246374, -97.735028 30.245863, -97.73502099999999 30.24544, -97.73503699999998 30.244959, -97.735142 30.244414, -97.73526099999999 30.244083, -97.73530699999998 30.243955, -97.73546699999999 30.243563, -97.735631 30.243214, -97.73566388253931 30.24316000768235, -97.76536643966915 30.24316000768235))
```

### Python 3.5
```python
Traceback (most recent call last):
  File "shapely_bytes_load.py", line 6, in <module>
    shp = wkb.loads(geom, hex=True)
  File "/Users/bcollins/anaconda/envs/grendel3/lib/python3.5/site-packages/shapely/wkb.py", line 14, in loads
    return reader.read_hex(data)
  File "/Users/bcollins/anaconda/envs/grendel3/lib/python3.5/site-packages/shapely/geos.py", line 384, in read_hex
    data = data.encode('ascii')
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by georgeouzou** [comment]
When using the function **wkb.loads** with _hex = True_, the input must be a string and not a bytestring, as in documentation. The thing in python 2, _str_data is used for both [string and binary data](https://docs.python.org/3/howto/pyporting.html#text-versus-binary-d). So in order for your code to work in both python 2 and 3 change:
`geom = b'0103000000010000007F00000070F584C3FB...' `
to:
`geom = '0103000000010000007F00000070F584C3FB...`

**Comment by sgillies** [comment]
Thanks, George!

**Comment by sgillies** [comment]
Thanks, George!

I'll make sure the docs reflect reality better and that we're testing this
case.
On Feb 13, 2016 2:34 PM, "George Ouzounoudis" <notifications@github.com>
wrote:

When using the function *wkb.loads* with *hex = True*, the input must be a
string and not a bytestring, as in documentation. The thing in python 2,
_str_data is used for both string and binary data
<https://docs.python.org/3/howto/pyporting.html#text-versus-binary-d>. So
in order for your code to work in both python 2 and 3 change:
geom = b'0103000000010000007F00000070F584C3FB...'
to:
geom = '0103000000010000007F00000070F584C3FB...

—
Reply to this email directly or view it on GitHub
<https://github.com/Toblerity/Shapely/issues/362#issuecomment-183759660>.

**Comment by brendancol** [comment]
Ahhh, Great thanks!
