### ISSUE TITLE
shapely.geometry and pyinstaller 3.1 issues

### ISSUE THREAD

**Issue by tacyd** [Toblerity/Shapely#368]
Hello guys,

I'm trying to freeze an app that uses shapely.geometry with PyInstaller on MacOS 10.9.5. 
The app works on the mac where it is frozen but on other macs it gives error:

`OSError: Could not find lib geos_c or load any of its variants /Users/fadmin/Downloads/qt-shapely-test.app/Contents/MacOS/libgeos_c.dylib.`

I have tried uselessly to find a solution. I use the --noupx option in pyinstaller and made sure the geos_c.dll and libgeos_c.dylib libs are actually in the .app folder. 
Also I edited the geos.py alt_paths to point to the correct location with:

`alt_paths = os.path.normpath(os.path.abspath(sys.executable+'/../libgeos_c.dylib'))`

rather than 

`alt_paths = [os.path.join(sys.executable, 'libgeos_c.dylib')]` as stated in [pull #261 ](https://github.com/Toblerity/Shapely/pull/261)

It points in the right place, libs are there but still the error.

In specific:
Pyinstaller 3.1
shapely.geometry 1.5.13_0 (MacPorts)
python 3.4 
MacOS 10.9.5
pyqt 5.5

The simplest app code to reproduce issue:

```	  
from PyQt5.QtWidgets import QApplication,QWidget,QLabel, QGroupBox, QGridLayout
from shapely.geometry import Polygon as Polygon_shapely
	  class Window(QWidget):
		 def __init__(self):
				super(Window, self).__init__()
				succ_lab = QLabel('worked')
				controls_lay = QGridLayout()
				controls_lay.addWidget(succ_lab)
				test_polygon = Polygon_shapely()
				self.setLayout(controls_lay)
				self.setWindowTitle("Shapely test")
			
	  if __name__ == '__main__':

    	import sys

    	app = QApplication(sys.argv)
    	window = Window()
    	window.show()
    	sys.exit(app.exec_())
```

The pyinstaller spec file:

```
a = Analysis(['/Users/tacyd/Dropbox/Python/random code/qt-shapely-test.py'],
             pathex=['/Users/tacyd/Python/pyinstaller-3.1/qt-shapely-test'],
             binaries=None,
             datas=None,
             hiddenimports=['ctypes.util','ctypes','distutils.util', 'shapely.geometry'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)

a.binaries = a.binaries + [('geos_c.dll', '/usr/local/lib/libgeos_c.dylib','BINARY')]

a.binaries = a.binaries + [('libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib','BINARY')]


pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='qt-shapely-test',
          debug=False,
          strip=False,
          upx=False,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               name='qt-shapely-test')
app = BUNDLE(coll,
             name='qt-shapely-test.app',
             icon=None,
             bundle_identifier=None)
```

Finally the error on a different mac:
```
/Users/fadmin/Downloads/qt-shapely-test.app/Contents/MacOS/qt-shapely-test ; exit;
fadmin@rri324d-mac:~$ /Users/fadmin/Downloads/qt-shapely-test.app/Contents/MacOS/qt-shapely-test ; exit;
pyinstaller geos
/Users/fadmin/Downloads/qt-shapely-test.app/Contents/MacOS/libgeos_c.dylib
Failed `CDLL(/Users/fadmin/Downloads/qt-shapely-test.app/Contents/MacOS/libgeos_c.dylib)`
Failed `CDLL(/)`
Failed `CDLL(U)`
Failed `CDLL(s)`
Failed `CDLL(e)`
Failed `CDLL(r)`
Failed `CDLL(s)`
Failed `CDLL(/)`
Failed `CDLL(f)`
Failed `CDLL(a)`
Failed `CDLL(d)`
Failed `CDLL(m)`
Failed `CDLL(i)`
Failed `CDLL(n)`
Failed `CDLL(/)`
Failed `CDLL(D)`
Failed `CDLL(o)`
Failed `CDLL(w)`
Failed `CDLL(n)`
Failed `CDLL(l)`
Failed `CDLL(o)`
Failed `CDLL(a)`
Failed `CDLL(d)`
Failed `CDLL(s)`
Failed `CDLL(/)`
Failed `CDLL(q)`
Failed `CDLL(t)`
Failed `CDLL(-)`
Failed `CDLL(s)`
Failed `CDLL(h)`
Failed `CDLL(a)`
Failed `CDLL(p)`
Failed `CDLL(e)`
Failed `CDLL(l)`
Failed `CDLL(y)`
Failed `CDLL(-)`
Failed `CDLL(t)`
Failed `CDLL(e)`
Failed `CDLL(s)`
Failed `CDLL(t)`
Failed `CDLL(.)`
Failed `CDLL(a)`
Failed `CDLL(p)`
Failed `CDLL(p)`
Failed `CDLL(/)`
Failed `CDLL(C)`
Failed `CDLL(o)`
Failed `CDLL(n)`
Failed `CDLL(t)`
Failed `CDLL(e)`
Failed `CDLL(n)`
Failed `CDLL(t)`
Failed `CDLL(s)`
Failed `CDLL(/)`
Failed `CDLL(M)`
Failed `CDLL(a)`
Failed `CDLL(c)`
Failed `CDLL(O)`
Failed `CDLL(S)`
Failed `CDLL(/)`
Failed `CDLL(l)`
Failed `CDLL(i)`
Failed `CDLL(b)`
Failed `CDLL(g)`
Failed `CDLL(e)`
Failed `CDLL(o)`
Failed `CDLL(s)`
Failed `CDLL(_)`
Failed `CDLL(c)`
Failed `CDLL(.)`
Failed `CDLL(d)`
Failed `CDLL(y)`
Failed `CDLL(l)`
Failed `CDLL(i)`
Failed `CDLL(b)`
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/Users/tacyd/Python/pyinstaller-3.1/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/shapely/geometry/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/Users/tacyd/Python/pyinstaller-3.1/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/shapely/geometry/base.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/Users/tacyd/Python/pyinstaller-3.1/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/shapely/coords.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/Users/tacyd/Python/pyinstaller-3.1/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/shapely/geos.py", line 139, in <module>
  File "site-packages/shapely/geos.py", line 61, in load_dll
OSError: Could not find lib geos_c or load any of its variants /Users/fadmin/Downloads/qt-shapely-test.app/Contents/MacOS/libgeos_c.dylib.
qt-shapely-test returned -1
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by sgillies** [comment]
@tacyd I'm not familiar with pyinstaller, but since I'm not doing anything out of the ordinary with respect to ctypes and GEOS, I suspect there's some issue between pyinstaller and ctypes. I noticed in a search that there are a number of reported issues: https://www.google.com/search?q=pyinstaller+ctypes&ie=utf-8&oe=utf-8.

**Comment by tacyd** [comment]
@sgillies Thank you, I had a feeling this was ctypes related but wanted to make sure about it. Will try check with pyinstaller team.

**Comment by sgillies** [comment]
Please follow up here if there's anything I can do in the Shapely code or docs, okay?

**Comment by tacyd** [comment]
Thank you, I'm linking the issue I opened on pyinstaller **[here](https://github.com/pyinstaller/pyinstaller/issues/1792)** for anybody in the future.

**Comment by sgillies** [comment]
Resolved in https://github.com/pyinstaller/pyinstaller/issues/1792.
