### ISSUE TITLE
OSX (10.10.5) fails to load GEOX framework

### ISSUE THREAD

**Issue by mromanie** [Toblerity/Shapely#394]
I'm running OS X 10.10.5 and python, GEOS and shapely from MacPorts:

>>> from shapely.geometry import Point
Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/shapely/geometry/base.py", line 9, in <module>
    from shapely.coords import CoordinateSequence
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/shapely/geos.py", line 98, in <module>
    free = load_dll('c').free
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/shapely/geos.py", line 61, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib c or load any of its variants [].

I've also tried GEOS from homebrew and kyngchaos' framework (http://www.kyngchaos.com/software/frameworks), but the result is always the same.

Could you, please, advise? Thanks!!

**Comment by sgillies** [comment]
> OSError: Could not find lib c or load any of its variants [].

I'm so sorry, but I don't know how to help if ctypes can not find libc on your system.

**Comment by mromanie** [comment]
Many thanks for the answer! It turns out that I needed to unset the environment variable DYLD_FALLBACK_LIBRARY_PATH, after which everything works just fine (the package is brilliant, by the way!). Maybe my experience can be of use to others, as well.

**Comment by douglowe** [comment]
Your experience is definitely useful to others. I had the same problem (on OSX too), and the recommended solution of unsetting DYLD_FALLBACK_LIBRARY_PATH has worked for me too - thanks!
