### ISSUE TITLE
VersionConflict: (packaging 15.3 (Shapely), Requirement.parse('packaging>=16.8'))

### ISSUE THREAD

**Issue by gcarq** [Toblerity/Shapely#468]
Hi i'm using the latest Shapely version `1.6b3` with CPython 3.6.0, but since a few days it fails on our CI infrastructure because of this version conflict.
See the jenkins log below:

```
12:49:10 + pip install -U pip
12:49:10 Requirement already up-to-date: pip in /var/jenkins_home/shiningpanda/jobs/ac7a9a05/virtualenvs/d41d8cd9/lib/python3.6/site-packages
12:49:10 + pip install --quiet packaging nose2 cov-core
12:49:11 + pip install -r requirements.txt
12:49:11 Collecting arrow==0.10.0 (from -r requirements.txt (line 3))
12:49:12 Collecting packaging==15.3 (from -r requirements.txt (line 6))
12:49:12   Using cached packaging-15.3-py2.py3-none-any.whl
12:49:12 Collecting pyramid_debugtoolbar==3.0.2 (from -r requirements.txt (line 7))
12:49:12   Using cached pyramid_debugtoolbar-3.0.2-py2.py3-none-any.whl
12:49:12 Collecting pyramid_health==1.2.1 (from -r requirements.txt (line 8))
12:49:12 Collecting pyramid==1.7.3 (from -r requirements.txt (line 9))
12:49:12   Using cached pyramid-1.7.3-py2.py3-none-any.whl
12:49:12 Collecting requests==2.12.4 (from -r requirements.txt (line 10))
12:49:13   Using cached requests-2.12.4-py2.py3-none-any.whl
12:49:13 Collecting Shapely==1.6b3 (from -r requirements.txt (line 11))
12:49:13   Using cached Shapely-1.6b3.tar.gz
12:49:13     Complete output from command python setup.py egg_info:
12:49:13     Traceback (most recent call last):
12:49:13       File "<string>", line 1, in <module>
12:49:13       File "/tmp/pip-build-ma0na333/Shapely/setup.py", line 373, in <module>
12:49:13         setup(ext_modules=ext_modules, **setup_args)
12:49:13       File "/opt/pyenv/versions/3.6.0/lib/python3.6/distutils/core.py", line 108, in setup
12:49:13         _setup_distribution = dist = klass(attrs)
12:49:13       File "/var/jenkins_home/shiningpanda/jobs/ac7a9a05/virtualenvs/d41d8cd9/lib/python3.6/site-packages/setuptools/dist.py", line 320, in __init__
12:49:13         _Distribution.__init__(self, attrs)
12:49:13       File "/opt/pyenv/versions/3.6.0/lib/python3.6/distutils/dist.py", line 281, in __init__
12:49:13         self.finalize_options()
12:49:13       File "/var/jenkins_home/shiningpanda/jobs/ac7a9a05/virtualenvs/d41d8cd9/lib/python3.6/site-packages/setuptools/dist.py", line 386, in finalize_options
12:49:13         ep.require(installer=self.fetch_build_egg)
12:49:13       File "/var/jenkins_home/shiningpanda/jobs/ac7a9a05/virtualenvs/d41d8cd9/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in require
12:49:13         items = working_set.resolve(reqs, env, installer, extras=self.extras)
12:49:13       File "/var/jenkins_home/shiningpanda/jobs/ac7a9a05/virtualenvs/d41d8cd9/lib/python3.6/site-packages/pkg_resources/__init__.py", line 859, in resolve
12:49:13         raise VersionConflict(dist, req).with_context(dependent_req)
12:49:13     pkg_resources.VersionConflict: (packaging 15.3 (/tmp/pip-build-ma0na333/Shapely), Requirement.parse('packaging>=16.8'))
12:49:13     
12:49:13     ----------------------------------------
12:49:13 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ma0na333/Shapely/
12:49:13 Build step 'Virtualenv Builder' marked build as failure
12:49:13 Skipping Cobertura coverage report as build was not UNSTABLE or better ...
12:49:13 Recording test results
```

However if I try to pin `packaging==15.3` then it fails with: 

```
11:41:13   Found existing installation: packaging 16.8
11:41:13     Uninstalling packaging-16.8:
11:41:13       Successfully uninstalled packaging-16.8
11:41:13 Successfully installed Mako-1.0.6 MarkupSafe-0.23 PasteDeploy-1.5.2 Pygments-2.2.0 SQLAlchemy-1.1.4 Shapely-1.6b3 WebOb-1.7.1 arrow-0.10.0 packaging-15.3 pyramid-1.7.3 pyramid-debugtoolbar-3.0.2 pyramid-health-1.2.1 pyramid-mako-1.0.2 python-dateutil-2.6.0 repoze.lru-0.6 requests-2.12.4 shortuuid-0.4.3 translationstring-1.3 urllib3-1.20 venusian-1.0 waitress-1.0.1 wrapt-1.10.8 zope.deprecation-4.2.0 zope.interface-4.3.3
11:41:13 + pip install '.[testing]'
11:41:14 Processing /var/jenkins_home/workspace/test_service-01
11:41:14 Could not import setuptools which is required to install from a source distribution.
11:41:14 Traceback (most recent call last):
11:41:14   File "/var/jenkins_home/shiningpanda/jobs/ac7a9a05/virtualenvs/d41d8cd9/lib/python3.6/site-packages/pip/req/req_install.py", line 387, in setup_py
11:41:14     import setuptools  # noqa
11:41:14   File "/var/jenkins_home/shiningpanda/jobs/ac7a9a05/virtualenvs/d41d8cd9/lib/python3.6/site-packages/setuptools/__init__.py", line 12, in <module>
11:41:14     import setuptools.version
11:41:14   File "/var/jenkins_home/shiningpanda/jobs/ac7a9a05/virtualenvs/d41d8cd9/lib/python3.6/site-packages/setuptools/version.py", line 1, in <module>
11:41:14     import pkg_resources
11:41:14   File "/var/jenkins_home/shiningpanda/jobs/ac7a9a05/virtualenvs/d41d8cd9/lib/python3.6/site-packages/pkg_resources/__init__.py", line 72, in <module>
11:41:14     import packaging.requirements
11:41:14 ModuleNotFoundError: No module named 'packaging.requirements'
```

**Comment by sgillies** [comment]
@gcarq Shapely includes packaging 16.7 in source distributions, but I've made a mistake in including the dist-info for 15.3. See below:

```
$ tar tzvf ~/Downloads/Shapely-1.6b3.tar.gz
drwxr-xr-x  0 sean   staff       0 Dec 31 10:52 Shapely-1.6b3/
-rw-r--r--  0 sean   staff   16097 Dec 31 10:52 Shapely-1.6b3/CHANGES.txt
-rw-r--r--  0 sean   staff    2414 Dec 31 10:52 Shapely-1.6b3/CREDITS.txt
drwxr-xr-x  0 sean   staff       0 Dec 31 10:52 Shapely-1.6b3/docs/
-rw-r--r--  0 sean   staff    1411 Dec 31 10:52 Shapely-1.6b3/docs/design.rst
-rw-r--r--  0 sean   staff     256 Dec 31 10:52 Shapely-1.6b3/docs/index.rst
-rw-r--r--  0 sean   staff   79156 Dec 31 10:52 Shapely-1.6b3/docs/manual.rst
-rw-r--r--  0 sean   staff      86 Dec 31 10:52 Shapely-1.6b3/docs/project.rst
-rw-r--r--  0 sean   staff    1519 Dec 31 10:52 Shapely-1.6b3/LICENSE.txt
drwxr-xr-x  0 sean   staff       0 Dec 31 10:52 Shapely-1.6b3/packaging/
-rw-r--r--  0 sean   staff     720 Dec 31 10:52 Shapely-1.6b3/packaging/__about__.py
-rw-r--r--  0 sean   staff     513 Dec 31 10:52 Shapely-1.6b3/packaging/__init__.py
-rw-r--r--  0 sean   staff     860 Dec 31 10:52 Shapely-1.6b3/packaging/_compat.py
-rw-r--r--  0 sean   staff    1416 Dec 31 10:52 Shapely-1.6b3/packaging/_structures.py
-rw-r--r--  0 sean   staff    7876 Dec 31 10:52 Shapely-1.6b3/packaging/markers.py
-rw-r--r--  0 sean   staff    4271 Dec 31 10:52 Shapely-1.6b3/packaging/requirements.py
-rw-r--r--  0 sean   staff   28025 Dec 31 10:52 Shapely-1.6b3/packaging/specifiers.py
-rw-r--r--  0 sean   staff     421 Dec 31 10:52 Shapely-1.6b3/packaging/utils.py
-rw-r--r--  0 sean   staff   11556 Dec 31 10:52 Shapely-1.6b3/packaging/version.py
drwxr-xr-x  0 sean   staff       0 Dec 31 10:52 Shapely-1.6b3/packaging-15.3.dist-info/
-rw-r--r--  0 sean   staff    3108 Dec 31 10:52 Shapely-1.6b3/packaging-15.3.dist-info/DESCRIPTION.rst
-rw-r--r--  0 sean   staff    3854 Dec 31 10:52 Shapely-1.6b3/packaging-15.3.dist-info/METADATA
-rw-r--r--  0 sean   staff     859 Dec 31 10:52 Shapely-1.6b3/packaging-15.3.dist-info/metadata.json
-rw-r--r--  0 sean   staff      46 Dec 31 10:52 Shapely-1.6b3/packaging-15.3.dist-info/pbr.json
-rw-r--r--  0 sean   staff    1068 Dec 31 10:52 Shapely-1.6b3/packaging-15.3.dist-info/RECORD
-rw-r--r--  0 sean   staff      10 Dec 31 10:52 Shapely-1.6b3/packaging-15.3.dist-info/top_level.txt
-rw-r--r--  0 sean   staff     110 Dec 31 10:52 Shapely-1.6b3/packaging-15.3.dist-info/WHEEL
...
```

I'll make a 1.6b4 to address this bug.

**Comment by gcarq** [comment]
Thanks for the quick response. It seems like an issue with the latest setuptools release, because it requires packaging 18.6,d owngrading setuptools works as a quick workaround.
