### ISSUE TITLE
"figures" not installing via pip, not called from doc example correctly

### ISSUE THREAD

**Issue by drscotthawley** [Toblerity/Shapely#536]
## Please note

If you are reporting an installation or module import issue, please note that
this project only accepts reports about problems with packages downloaded from
the Python Package Index. Conda users should take issues to one of the
following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/shapely-feedstock

## Expected behavior and actual behavior.

Be able to run an example from the documentation. 
Instead receive "ImportError: No module named 'figures'"

## Steps to reproduce the problem.

Install shapely via pip:
$ pip install shapely
Collecting shapely
  Downloading Shapely-1.6.1-cp35-cp35m-macosx_10_6_intel.whl (2.6MB)
    100% |████████████████████████████████| 2.6MB 260kB/s 
Installing collected packages: shapely
Successfully installed shapely-1.6.1

Download example 'Source code' file from documentation (re. intersection & union at https://shapely.readthedocs.io/en/latest/manual.html): 
$ curl -O https://shapely.readthedocs.io/en/latest/code/intersection-sym-difference.py

Try to run it
$ python intersection-sym-difference.py 
Traceback (most recent call last):
  File "intersection-sym-difference.py", line 5, in <module>
    from figures import SIZE, BLUE, GRAY, set_limits
ImportError: No module named 'figures'

Try to find figures
$ locate shapely 
(get lots of files listed)
$ locate shapely | grep figures
(nothing)

**To fix:**
Download [figures.py](https://raw.githubusercontent.com/Toblerity/Shapely/master/docs/code/figures.py) manually.  Install in shapely directory. Change call in documentation example source code from 

`from figures import SIZE, BLUE, GRAY, set_limits
`
to
`from shapely.figures import SIZE, BLUE, GRAY, set_limits
`

## Operating system

Mac OS X 10.12.6

## Shapely version and provenance

1.6.1 from PyPI using pip

**Comment by sgillies** [comment]
Yes, this is a bug. I think my solution will be to eliminate the option to download the source of the plots. I only want to provide some illustrations, I don't want to maintain code that uses maplotlib.

**Comment by drscotthawley** [comment]
Obviously do what you like with your own code,  however I think that would be an unfortunate choice for some users, as I only found out about Shapely because I was searching on how to *draw* intersection & union of my sets.

**Comment by BenBlumer** [comment]
@sgillies totally up you. I appreciate the Shapely library. But the ability to actually draw the geometries you create in Shapely is realllllly valuable.

**Comment by bonashen** [comment]
> ## Please note
> If you are reporting an installation or module import issue, please note that
> this project only accepts reports about problems with packages downloaded from
> the Python Package Index. Conda users should take issues to one of the
> following trackers:
> 
> * https://github.com/ContinuumIO/anaconda-issues/issues
> * https://github.com/conda-forge/shapely-feedstock
> 
> ## Expected behavior and actual behavior.
> Be able to run an example from the documentation.
> Instead receive "ImportError: No module named 'figures'"
> 
> ## Steps to reproduce the problem.
> Install shapely via pip:
> $ pip install shapely
> Collecting shapely
> Downloading Shapely-1.6.1-cp35-cp35m-macosx_10_6_intel.whl (2.6MB)
> 100% |████████████████████████████████| 2.6MB 260kB/s
> Installing collected packages: shapely
> Successfully installed shapely-1.6.1
> 
> Download example 'Source code' file from documentation (re. intersection & union at https://shapely.readthedocs.io/en/latest/manual.html):
> $ curl -O https://shapely.readthedocs.io/en/latest/code/intersection-sym-difference.py
> 
> Try to run it
> $ python intersection-sym-difference.py
> Traceback (most recent call last):
> File "intersection-sym-difference.py", line 5, in 
> from figures import SIZE, BLUE, GRAY, set_limits
> ImportError: No module named 'figures'
> 
> Try to find figures
> $ locate shapely
> (get lots of files listed)
> $ locate shapely | grep figures
> (nothing)
> 
> **To fix:**
> Download [figures.py](https://raw.githubusercontent.com/Toblerity/Shapely/master/docs/code/figures.py) manually. Install in shapely directory. Change call in documentation example source code from
> 
> `from figures import SIZE, BLUE, GRAY, set_limits `
> to
> `from shapely.figures import SIZE, BLUE, GRAY, set_limits `
> 
> ## Operating system
> Mac OS X 10.12.6
> 
> ## Shapely version and provenance
> 1.6.1 from PyPI using pip

>**pip list**
Package         Version
--------------- -----------
certifi         2018.8.24
cycler          0.10.0
descartes       1.1.0
**figures         0.0.0**
kiwisolver      1.0.1
matplotlib      3.0.1
mkl-fft         1.0.6
mkl-random      1.0.1
numpy           1.15.2
pip             18.0
pyparsing       2.3.0
python-dateutil 2.7.5
pythonnet       2.3.0
setuptools      40.4.3
Shapely         1.6.4.post1
six             1.11.0
wheel           0.32.0
wincertstore    0.2

```bash
python linestring.py
``` 
Traceback (most recent call last):
  File "linestring.py", line 4, in <module>
    from figures import SIZE, set_limits, plot_coords, plot_bounds, plot_line_issimple
ImportError: cannot import name 'SIZE'

**Comment by ldpgh** [comment]
Shapely has been installed using    `python -m pip install shapely`

Sub-Module descartes has not been installed. Have been installed manually.

While trying  example
    https://shapely.readthedocs.io/en/latest/code/buffer.py
issue regarding `figures `seems to be still there ...

1. Btw. there seems to be a public `figures `module returned by  `pip install figures`
2. Github-Search@ThisRepo does not find `figures.py`  in this repo ... though the link   https://github.com/Toblerity/Shapely/search?q=figures.py&unscoped_q=figures.py given above returns the file.

```
C:\Users\aha>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from matplotlib import pyplot
>>> from shapely.geometry import LineString
>>> from descartes import PolygonPatch
>>>
>>> from figures import SIZE, BLUE, GRAY, set_limits, plot_line
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'SIZE' from 'figures' (C:\Programme\Python\Python37-32\lib\site-packages\figures\__init__.py)
>>>

>>> import shapely
>>> shapely.__version__
'1.7.0'

>>> from figures import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'figures'

```

**Comment by ldpgh** [comment]
... with `figures.py` residing in  `shapely.docs.code`  the regular installed `shapely` module can not find it.

**Comment by sgillies** [comment]
Thanks, folks. It's labeled as a bug and we'll deal with it. There are higher priority issues to deal with at the moment.

**Comment by caozhou** [comment]
> ## Please note
> If you are reporting an installation or module import issue, please note that
> this project only accepts reports about problems with packages downloaded from
> the Python Package Index. Conda users should take issues to one of the
> following trackers:
> 
> * https://github.com/ContinuumIO/anaconda-issues/issues
> * https://github.com/conda-forge/shapely-feedstock
> 
> ## Expected behavior and actual behavior.
> Be able to run an example from the documentation.
> Instead receive "ImportError: No module named 'figures'"
> 
> ## Steps to reproduce the problem.
> Install shapely via pip:
> $ pip install shapely
> Collecting shapely
> Downloading Shapely-1.6.1-cp35-cp35m-macosx_10_6_intel.whl (2.6MB)
> 100% |████████████████████████████████| 2.6MB 260kB/s
> Installing collected packages: shapely
> Successfully installed shapely-1.6.1
> 
> Download example 'Source code' file from documentation (re. intersection & union at https://shapely.readthedocs.io/en/latest/manual.html):
> $ curl -O https://shapely.readthedocs.io/en/latest/code/intersection-sym-difference.py
> 
> Try to run it
> $ python intersection-sym-difference.py
> Traceback (most recent call last):
> File "intersection-sym-difference.py", line 5, in
> from figures import SIZE, BLUE, GRAY, set_limits
> ImportError: No module named 'figures'
> 
> Try to find figures
> $ locate shapely
> (get lots of files listed)
> $ locate shapely | grep figures
> (nothing)
> 
> **To fix:**
> Download [figures.py](https://raw.githubusercontent.com/Toblerity/Shapely/master/docs/code/figures.py) manually. Install in shapely directory. Change call in documentation example source code from
> 
> `from figures import SIZE, BLUE, GRAY, set_limits `
> to
> `from shapely.figures import SIZE, BLUE, GRAY, set_limits `
> 
> ## Operating system
> Mac OS X 10.12.6
> 
> ## Shapely version and provenance
> 1.6.1 from PyPI using pip

yeal, it solves my problem, so in short, just copy the [figures.py](https://github.com/Toblerity/Shapely/search?q=figures.py&unscoped_q=figures.py) file to the shapely install directory. For my case, the shapely install directory is '$python_install_dir/Lib/site-packages/shapely', where $$python_install_dir is where you python is installed.

**Comment by sgillies** [comment]
The solution here is to cd to docs/code and run the examples from there. The doc examples are going to get a rework for 2.0 and the figures module will go away.

**Comment by josse7cz** [comment]
Download [figures.py](https://raw.githubusercontent.com/Toblerity/Shapely/master/docs/code/figures.py) manually. Its work for me.
