### ISSUE TITLE
Hi guys I've been digging my mind to resolve this issue ,I tried all versions of shapely ,unfortunately  I got nothing .Please help me.  File "/home/user/PycharmProjects/project/utils.py", line 335, in plot_coords     x, y = ob.xy   File "/home/user/.local/lib/python2.7/site-packages/shapely/geometry/base.py", line 335, in xy     raise NotImplementedError NotImplementedError 

### ISSUE THREAD

**Issue by Shimaa1** [Toblerity/Shapely#576]
## Please note

If you are reporting an installation or module import issue, please note that
this project only accepts reports about problems with packages downloaded from
the Python Package Index. Conda users should take issues to one of the
following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/shapely-feedstock

## Expected behavior and actual behavior.

(For example: the area of my geometry is `1.417` when it should be `1.414`.)

## Steps to reproduce the problem.

(For example, a script with required data)

## Operating system

(For example, Mac OS X 10.12.3)

## Shapely version and provenance

(For example, 1.6b4 installed from PyPI using pip)

**Comment by sgillies** [comment]
It looks to me like you are attempting to get the xy array of a Polygon. This will not work. The `xy` method is only implemented for `Point`, `MultiPoint`, `LineString`, and `LinearRing`, objects that have a coordinate sequence. You can call `Polygon.exterior.xy` to get the coordinates of a polygon's exterior ring.

```python
>>> from shapely.geometry import Point
>>> Point(0, 0).xy
(array('d', [0.0]), array('d', [0.0]))
>>> Point(0, 0).buffer(1.0).exterior.xy
(array('d', [1.0, 0.9951847266721969, 0.9807852804032304, 0.9569403357322089, 0.923879532511287, 0.8819212643483553, 0.8314696123025456, 0.7730104533627374, 0.7071067811865481, 0.6343932841636463, 0.5555702330196032, 0.4713967368259986, 0.38268343236509084, 0.29028467725446355, 0.19509032201612964, 0.09801714032956209, 1.6155445744325867e-15, -0.09801714032955888, -0.19509032201612647, -0.2902846772544605, -0.38268343236508784, -0.4713967368259957, -0.5555702330196004, -0.6343932841636439, -0.7071067811865461, -0.7730104533627358, -0.8314696123025443, -0.8819212643483543, -0.9238795325112862, -0.9569403357322085, -0.9807852804032302, -0.9951847266721968, -1.0, -0.9951847266721969, -0.9807852804032307, -0.956940335732209, -0.923879532511287, -0.8819212643483553, -0.8314696123025455, -0.7730104533627371, -0.7071067811865477, -0.6343932841636459, -0.555570233019603, -0.47139673682599864, -0.38268343236509117, -0.2902846772544641, -0.1950903220161304, -0.0980171403295631, -2.848232278972479e-15, 0.09801714032955744, 0.1950903220161248, 0.29028467725445867, 0.3826834323650859, 0.47139673682599365, 0.5555702330195982, 0.6343932841636415, 0.7071067811865436, 0.7730104533627332, 0.8314696123025418, 0.8819212643483519, 0.9238795325112841, 0.9569403357322068, 0.980785280403229, 0.9951847266721962, 1.0, 1.0]), array('d', [0.0, -0.0980171403295605, -0.19509032201612808, -0.2902846772544621, -0.3826834323650894, -0.4713967368259972, -0.5555702330196017, -0.6343932841636449, -0.707106781186547, -0.7730104533627363, -0.8314696123025447, -0.8819212643483545, -0.9238795325112863, -0.9569403357322085, -0.9807852804032302, -0.9951847266721967, -1.0, -0.995184726672197, -0.9807852804032308, -0.9569403357322095, -0.9238795325112875, -0.881921264348356, -0.8314696123025465, -0.7730104533627382, -0.7071067811865489, -0.6343932841636468, -0.5555702330196036, -0.47139673682599903, -0.3826834323650911, -0.2902846772544636, -0.19509032201612947, -0.09801714032956171, -1.0106430996148606e-15, 0.0980171403295597, 0.1950903220161275, 0.2902846772544617, 0.3826834323650892, 0.47139673682599725, 0.555570233019602, 0.6343932841636453, 0.7071067811865475, 0.7730104533627367, 0.8314696123025447, 0.8819212643483545, 0.9238795325112862, 0.9569403357322084, 0.98078528040323, 0.9951847266721966, 1.0, 0.9951847266721972, 0.9807852804032311, 0.9569403357322099, 0.9238795325112884, 0.8819212643483572, 0.831469612302548, 0.7730104533627402, 0.7071067811865515, 0.63439328416365, 0.5555702330196074, 0.4713967368260034, 0.3826834323650961, 0.29028467725446927, 0.1950903220161357, 0.09801714032956847, 8.238535137130597e-15, 0.0]))
>>> Point(0, 0).buffer(1.0).xy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/seang/envs/data/lib/python3.6/site-packages/shapely/geometry/base.py", line 335, in xy
    raise NotImplementedError
NotImplementedError
```

**Comment by Shimaa1** [comment]
@sgillies Thank you , but it worked earlier and this is how my code looks like;

 tx1 = desc1[10:13]
    ty1 = desc1[13:16]
    tx2 = desc2[10:13]
    ty2 = desc2[13:16]

    xy1 = [(tx1[i], ty1[i]) for i in range(tx1.shape[0])]
    xy2 = [(tx2[i], ty2[i]) for i in range(tx2.shape[0])]
    poly1 = Polygon(xy1)
    poly2 = Polygon(xy2)
    poly_i = poly1.intersection(poly2)
    ax = plt.subplot(111)
    plot_coords(ax, poly1)
    plot_bounds(ax, poly1)
    plot_coords(ax, poly2)
    plot_bounds(ax, poly2)
    plot_coords(ax, poly_i)
    plot_bounds(ax, poly_i)
    plt.show()
    vec.append(poly_i.area)
 vec.append(np.abs(action1-action2))
