### ISSUE TITLE
PointAdapter.wkt after ops.transform

### ISSUE THREAD

**Issue by Ngoguey42** [Toblerity/Shapely#582]
## Expected behavior and actual behavior.
No exception raised / exception raised

#### Code
```py
import shapely.geometry as sg
import shapely.ops as sops
import numpy as np
import shapely

print(shapely.__version__)
pt = sg.asShape(dict(type='Point', coordinates=np.asarray([672901.5639714902, 6876196.523897117])))
print(type(pt))
print(pt.wkt)
pt = sops.transform(lambda x, y, z=None: tuple(filter(None, [x, y, z])), pt)
print(type(pt))
print(pt.wkt)
```

#### Output
```
1.6.4.post1
<class 'shapely.geometry.point.PointAdapter'>
POINT (672901.5639714902 6876196.523897117)
<class 'shapely.geometry.point.PointAdapter'>
Traceback (most recent call last):
  File "fail.py", line 12, in <module>
    print(pt.wkt)
  File "/media/ngoguey/4b16cd43-a81f-4aef-b59e-6de3120df13b/rb/lib/python3.6/site-packages/shapely/geometry/base.py", line 367, in wkt
    return WKTWriter(lgeos, **kw).write(self)
  File "/media/ngoguey/4b16cd43-a81f-4aef-b59e-6de3120df13b/rb/lib/python3.6/site-packages/shapely/geos.py", line 361, in write
    if geom is None or geom._geom is None:
  File "/media/ngoguey/4b16cd43-a81f-4aef-b59e-6de3120df13b/rb/lib/python3.6/site-packages/shapely/geometry/proxy.py", line 33, in _geom
    if len(self.context) > 0:
TypeError: object of type 'zip' has no len()
```

## Operating system
OS: `Ubuntu 16.04.3 LTS`

## Shapely version and provenance
Version: `1.6.4.post1` from `conda-forge`

**Comment by sgillies** [comment]
@Ngoguey42 can you try `shape` instead and let us know if that works?

**Comment by Ngoguey42** [comment]
It works

**Comment by sgillies** [comment]
@Ngoguey42 thanks for the report. I've been encouraging users to switch to `shape` from `asShape` since https://github.com/Toblerity/Shapely/issues/124 and will go through the documentation again and look for more usage that can be changed over. We can't remove `asShape` from the library at 1.7 but we might make it an alias for `shape` in a future version, and so I'm going to mark this as an issue that won't be fixed.
