### ISSUE TITLE
MultiPolygon constructor behavior

### ISSUE THREAD

**Issue by Ricyteach** [Toblerity/Shapely#588]
## Expected behavior and actual behavior.

The `MultiPolygon` constructor seems to behave oddly when provided a sequence containing other `MP` objects.

[See behavior example on nbviewer.](http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/k8q1mkt0ywgihxg/multipolygon_constructor_behavior.ipynb)

## Steps to reproduce the problem.

see nbviewer link

## Operating system

Windows 10

## Shapely version and provenance

1.6.4 from [Chris Gohlke's whl file page](https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely)

**Comment by snorfalorpagus** [comment]
I think there are some issues with other Multi-type geometries also, although they raise unhelpful exceptions instead of silently doing the wrong thing.

Create some sample data:
```
>>> mp1 = MultiPoint([[0, 0], [1, 1]])
>>> mp2 = MultiPoint([[2, 2], [3, 3]])
```
Create a single MultiPoint containing all 4 points:
```
>>> mp3 = MultiPoint([*mp1.geoms, *mp2.geoms])
>>> len(mp3)
4
```
The same again, but passing in MultiPoints instead of Points.
```
>>> mp3 = MultiPoint([mp1.geoms, mp2.geoms])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snorf/.local/share/virtualenvs/wayleaves-service-nFyE-GgQ/lib/python3.6/site-packages/shapely/geometry/multipoint.py", line 58, in __init__
    self._geom, self._ndim = geos_multipoint_from_py(points)
  File "/home/snorf/.local/share/virtualenvs/wayleaves-service-nFyE-GgQ/lib/python3.6/site-packages/shapely/geometry/multipoint.py", line 172, in geos_multipoint_from_py
    geom, ndims = point.geos_point_from_py(coords)
  File "/home/snorf/.local/share/virtualenvs/wayleaves-service-nFyE-GgQ/lib/python3.6/site-packages/shapely/geometry/point.py", line 209, in geos_point_from_py
    dx = c_double(coords[0])
TypeError: must be real number, not Point
```
A mixture of MultiPoint and Point:
```
>>> mp3 = MultiPoint([mp1, Point(5,5)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snorf/.local/share/virtualenvs/wayleaves-service-nFyE-GgQ/lib/python3.6/site-packages/shapely/geometry/multipoint.py", line 58, in __init__
    self._geom, self._ndim = geos_multipoint_from_py(points)
  File "/home/snorf/.local/share/virtualenvs/wayleaves-service-nFyE-GgQ/lib/python3.6/site-packages/shapely/geometry/multipoint.py", line 172, in geos_multipoint_from_py
    geom, ndims = point.geos_point_from_py(coords)
  File "/home/snorf/.local/share/virtualenvs/wayleaves-service-nFyE-GgQ/lib/python3.6/site-packages/shapely/geometry/point.py", line 209, in geos_point_from_py
    dx = c_double(coords[0])
TypeError: must be real number, not Point
```
An invalid mixture containing a LineString:
```
>>> mp3 = MultiPoint([line, Point(5,5)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snorf/.local/share/virtualenvs/wayleaves-service-nFyE-GgQ/lib/python3.6/site-packages/shapely/geometry/multipoint.py", line 58, in __init__
    self._geom, self._ndim = geos_multipoint_from_py(points)
  File "/home/snorf/.local/share/virtualenvs/wayleaves-service-nFyE-GgQ/lib/python3.6/site-packages/shapely/geometry/multipoint.py", line 172, in geos_multipoint_from_py
    geom, ndims = point.geos_point_from_py(coords)
  File "/home/snorf/.local/share/virtualenvs/wayleaves-service-nFyE-GgQ/lib/python3.6/site-packages/shapely/geometry/point.py", line 202, in geos_point_from_py
    ob = list(ob)
TypeError: 'LineString' object is not iterable
```
My initial feeling is that it should be valid to create a MultiPoint by passing a list of existing MultiPoint objects, and that passing a non-point object should still raise an exception but a more useful one.

**Comment by Ricyteach** [comment]
If I may venture an opinion: I'm skeptical it's a good idea for a sequence of multi-geometry objects to produce another multi-geometry object. At bottom, these mutli-geometries are mostly just sequences with a few additional features. The behave similar 

Consider for example that if the proposed `MultiPoint` behavior- implicit unpacking of nested `MultiPoint`s- were implemented for regular python `list`, you'd be able to write code like this:

    x,y = [1,2,3],[4,5,6]
    z = list([x, y])
    assert z == [1,2,3,4,5,6] # <-- This would be kind of weird

I suppose this COULD be appropriate behavior for multi geometry objects but it could certainly be surprising if you're thinking of them as similar to built in data structures.  It seems better to me to require this kind of syntax which is equivalent to a builtin list:

    mp3 = MultiPoint([*mp1, *mp2, p1, p2])

**Comment by miker985** [comment]
@sgillies would you be amenable to raising an error instead of silently truncating the multipolygon instance passed to `MultiPolygon` to its first component polygon?
