### ISSUE TITLE
pip install on Windows issues

### ISSUE THREAD

**Issue by benCarmera** [Toblerity/Shapely#598]
Hi,

Having issues with installing Shapely on Windows using pip. Some issue with egg_info.

'  '  '  
C:\Users\>python -m pip install Shapely
Collecting Shapely
  Using cached https://files.pythonhosted.org/packages/7d/3c/0f09841db07aabf9cc387662be646f181d07ed196e6f60ce8be5f4a8f0bd/Shapely-1.6.4.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\\AppData\Local\Temp\pip-install-0x6irwxa\Shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\\AppData\Local\Temp\pip-install-0x6irwxa\Shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Users\\AppData\Local\Programs\Python\Python36-32\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\\AppData\Local\Temp\pip-install-0x6irwxa\Shapely\
'  '  '

Unsure the next step is.

**Comment by sgillies** [comment]
Shapely cannot be installed from PyPI on Windows. You must use Anaconda or the wheels that Christophe Gohlke distributes: https://github.com/Toblerity/Shapely#built-distributions.
