### ISSUE TITLE
install shapely on msys2

### ISSUE THREAD

**Issue by schelmo** [Toblerity/Shapely#633]
i cant install shapely on msys2 via pip

## Expected behavior and actual behavior.
should install

## Steps to reproduce the problem.
install msys2, then:
```
# pacman -S mingw-w64-x86_64-python3-pip  mingw-w64-x86_64-geos-3.6.3-1
# which geos-config
/mingw64/bin/geos-config
# pip3 install shapely
Collecting shapely
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:/Users/User/AppData/Local/Temp/pip-install-xl0imn6i/shapely/setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:/Users/User/AppData/Local/Temp/pip-install-xl0imn6i/shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:/Users/User/msys64/mingw64/lib/python3.7\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:/Users/User/AppData/Local/Temp/pip-install-xl0imn6i/shapely/
```
## Operating system
Windows 7 64bit with Msys2

## Shapely version and provenance
Shapely-1.6.4.post2 from pip

**Comment by snorfalorpagus** [comment]
Translation:
> Das angegebene Modul wurde nicht gefunden
> The specified module was not found

**Comment by schelmo** [comment]
okey tried it without pip
the library is named libgeos_c.dll and not just geos_c.dll
```
$ pacman -Ql mingw-w64-x86_64-geos
mingw-w64-x86_64-geos /mingw64/
mingw-w64-x86_64-geos /mingw64/bin/
mingw-w64-x86_64-geos /mingw64/bin/geos-config
mingw-w64-x86_64-geos /mingw64/bin/libgeos.dll
mingw-w64-x86_64-geos /mingw64/bin/libgeos_c.dll
mingw-w64-x86_64-geos /mingw64/include/
mingw-w64-x86_64-geos /mingw64/include/geos/
...
...
...
mingw-w64-x86_64-geos /mingw64/include/geos_c.h
mingw-w64-x86_64-geos /mingw64/lib/
mingw-w64-x86_64-geos /mingw64/lib/libgeos.a
mingw-w64-x86_64-geos /mingw64/lib/libgeos.dll.a
mingw-w64-x86_64-geos /mingw64/lib/libgeos_c.dll.a
```
so i replaced geos_c.dll with libgeos_c.dll in shapely/_buildcfg.py and shapely/geos.py 
then i could install it (but without the C Extension) with:
```
$ CFLAGS="$(/mingw64/bin/geos-config --cflags)" LDFLAGS="$(/mingw64/bin/geos-config --clibs)" python3 setup.py install
setup.py:159: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "checked on import of shapely.", exc)
WARNING:setup.py:Failed to determine system's GEOS version: Could not find geos-config script. Installation continuing. GEOS version will be checked on import of shapely.
C:/Users/User/msys64/mingw64/lib/python3.7\distutils\dist.py:274: UserWarning: Unknown distribution option: 'extras_require'
  warnings.warn(msg)
C:/Users/User/msys64/mingw64/lib/python3.7\distutils\dist.py:274: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib.mingw-3.7
creating build/lib.mingw-3.7/shapely
copying shapely/affinity.py -> build/lib.mingw-3.7/shapely
copying shapely/coords.py -> build/lib.mingw-3.7/shapely
copying shapely/ctypes_declarations.py -> build/lib.mingw-3.7/shapely
copying shapely/errors.py -> build/lib.mingw-3.7/shapely
copying shapely/ftools.py -> build/lib.mingw-3.7/shapely
copying shapely/geos.py -> build/lib.mingw-3.7/shapely
copying shapely/impl.py -> build/lib.mingw-3.7/shapely
copying shapely/iterops.py -> build/lib.mingw-3.7/shapely
copying shapely/linref.py -> build/lib.mingw-3.7/shapely
copying shapely/ops.py -> build/lib.mingw-3.7/shapely
copying shapely/predicates.py -> build/lib.mingw-3.7/shapely
copying shapely/prepared.py -> build/lib.mingw-3.7/shapely
copying shapely/strtree.py -> build/lib.mingw-3.7/shapely
copying shapely/topology.py -> build/lib.mingw-3.7/shapely
copying shapely/validation.py -> build/lib.mingw-3.7/shapely
copying shapely/wkb.py -> build/lib.mingw-3.7/shapely
copying shapely/wkt.py -> build/lib.mingw-3.7/shapely
copying shapely/_buildcfg.py -> build/lib.mingw-3.7/shapely
copying shapely/__init__.py -> build/lib.mingw-3.7/shapely
creating build/lib.mingw-3.7/shapely/geometry
copying shapely/geometry/base.py -> build/lib.mingw-3.7/shapely/geometry
copying shapely/geometry/collection.py -> build/lib.mingw-3.7/shapely/geometry
copying shapely/geometry/geo.py -> build/lib.mingw-3.7/shapely/geometry
copying shapely/geometry/linestring.py -> build/lib.mingw-3.7/shapely/geometry
copying shapely/geometry/multilinestring.py -> build/lib.mingw-3.7/shapely/geometry
copying shapely/geometry/multipoint.py -> build/lib.mingw-3.7/shapely/geometry
copying shapely/geometry/multipolygon.py -> build/lib.mingw-3.7/shapely/geometry
copying shapely/geometry/point.py -> build/lib.mingw-3.7/shapely/geometry
copying shapely/geometry/polygon.py -> build/lib.mingw-3.7/shapely/geometry
copying shapely/geometry/proxy.py -> build/lib.mingw-3.7/shapely/geometry
copying shapely/geometry/__init__.py -> build/lib.mingw-3.7/shapely/geometry
creating build/lib.mingw-3.7/shapely/algorithms
copying shapely/algorithms/cga.py -> build/lib.mingw-3.7/shapely/algorithms
copying shapely/algorithms/polylabel.py -> build/lib.mingw-3.7/shapely/algorithms
copying shapely/algorithms/__init__.py -> build/lib.mingw-3.7/shapely/algorithms
creating build/lib.mingw-3.7/shapely/examples
copying shapely/examples/dissolve.py -> build/lib.mingw-3.7/shapely/examples
copying shapely/examples/geoms.py -> build/lib.mingw-3.7/shapely/examples
copying shapely/examples/intersect.py -> build/lib.mingw-3.7/shapely/examples
copying shapely/examples/__init__.py -> build/lib.mingw-3.7/shapely/examples
creating build/lib.mingw-3.7/shapely/speedups
copying shapely/speedups/__init__.py -> build/lib.mingw-3.7/shapely/speedups
creating build/lib.mingw-3.7/shapely/vectorized
copying shapely/vectorized/__init__.py -> build/lib.mingw-3.7/shapely/vectorized
running build_ext
building 'shapely.speedups._speedups' extension
creating build/temp.mingw-3.7
creating build/temp.mingw-3.7/shapely
creating build/temp.mingw-3.7/shapely/speedups
C:\Users\User\msys64\mingw64\bin/x86_64-w64-mingw32-gcc.exe -DNDEBUG -IC:/Users/User/msys64/mingw64/include -IC:/Users/User/msys64/mingw64/include/python3.7m -c shapely/speedups/_speedups.c -o build/temp.mingw-3.7/shapely/speedups/_speedups.o
writing build/temp.mingw-3.7/shapely/speedups/_speedups-cpython-37m.def
C:\Users\User\msys64\mingw64\bin/x86_64-w64-mingw32-gcc.exe -shared -Wl,--enable-auto-image-base -pipe -s -pipe -s -LC:/Users/User/msys64/mingw64/lib -lgeos_c -IC:/Users/User/msys64/mingw64/include -s build/temp.mingw-3.7/shapely/speedups/_speedups.o build/temp.mingw-3.7/shapely/speedups/_speedups-cpython-37m.def -LC:/Users/User/msys64/mingw64/lib/python3.7/config-3.7m -LC:/Users/User/msys64/mingw64/lib -lpython3.7m -lversion -lshlwapi -o build/lib.mingw-3.7/shapely/speedups/_speedups-cpython-37m.dll
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x901): undefined reference to `GEOSGeom_destroy_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x2469): undefined reference to `GEOSHasZ_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x26b8): undefined reference to `GEOSGeom_clone_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x27e1): undefined reference to `GEOSGeom_getCoordSeq_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x27fe): undefined reference to `GEOSCoordSeq_clone_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x2883): undefined reference to `GEOSGeom_createLineString_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x524d): undefined reference to `GEOSGeom_getCoordSeq_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x55a7): undefined reference to `GEOSCoordSeq_create_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x56d2): undefined reference to `GEOSCoordSeq_setX_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x56fd): undefined reference to `GEOSCoordSeq_setY_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x5744): undefined reference to `GEOSCoordSeq_setZ_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x6df4): undefined reference to `GEOSGeom_getCoordSeq_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x714e): undefined reference to `GEOSCoordSeq_create_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x791e): undefined reference to `GEOSCoordSeq_setX_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x7949): undefined reference to `GEOSCoordSeq_setY_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x7990): undefined reference to `GEOSCoordSeq_setZ_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x7c3e): undefined reference to `GEOSGeom_createLineString_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x8a34): undefined reference to `GEOSHasZ_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x8c83): undefined reference to `GEOSGeom_clone_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x8dac): undefined reference to `GEOSGeom_getCoordSeq_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x8dd0): undefined reference to `GEOSCoordSeq_getSize_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x8de6): undefined reference to `GEOSisClosed_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x8e4c): undefined reference to `GEOSCoordSeq_clone_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x8ed1): undefined reference to `GEOSGeom_createLinearRing_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xb420): undefined reference to `GEOSGeom_getCoordSeq_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xb77a): undefined reference to `GEOSCoordSeq_create_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xb8a2): undefined reference to `GEOSCoordSeq_setX_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xb8cd): undefined reference to `GEOSCoordSeq_setY_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xb914): undefined reference to `GEOSCoordSeq_setZ_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xba0a): undefined reference to `GEOSCoordSeq_setX_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xba3a): undefined reference to `GEOSCoordSeq_setY_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xba86): undefined reference to `GEOSCoordSeq_setZ_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xd192): undefined reference to `GEOSGeom_getCoordSeq_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xd4ec): undefined reference to `GEOSCoordSeq_create_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xdaac): undefined reference to `GEOSCoordSeq_setX_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xdad7): undefined reference to `GEOSCoordSeq_setY_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xdb1e): undefined reference to `GEOSCoordSeq_setZ_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xe0e2): undefined reference to `GEOSCoordSeq_setX_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xe112): undefined reference to `GEOSCoordSeq_setY_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xe15e): undefined reference to `GEOSCoordSeq_setZ_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0xe3f3): undefined reference to `GEOSGeom_createLinearRing_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x10084): undefined reference to `GEOSCoordSeq_getX_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x100cb): undefined reference to `GEOSCoordSeq_getY_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x1012c): undefined reference to `GEOSCoordSeq_getZ_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x111c7): undefined reference to `GEOSCoordSeq_getX_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x11200): undefined reference to `GEOSCoordSeq_getY_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x11259): undefined reference to `GEOSCoordSeq_getZ_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x11bdc): undefined reference to `GEOSCoordSeq_getSize_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x11bf4): undefined reference to `GEOSCoordSeq_create_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x11c39): undefined reference to `GEOSCoordSeq_getX_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x11c59): undefined reference to `GEOSCoordSeq_getY_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x11cd8): undefined reference to `GEOSCoordSeq_setX_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x11cf7): undefined reference to `GEOSCoordSeq_setY_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x11d5f): undefined reference to `GEOSCoordSeq_getZ_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x11dbf): undefined reference to `GEOSCoordSeq_setZ_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x15302): undefined reference to `GEOSGeom_getCoordSeq_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x154f4): undefined reference to `GEOSGeom_createPoint_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x1562b): undefined reference to `GEOSGeom_createLineString_r'
C:/Users/User/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/temp.mingw-3.7/shapely/speedups/_speedups.o:_speedups.c:(.text+0x15762): undefined reference to `GEOSGeom_createLinearRing_r'
collect2.exe: error: ld returned 1 exit status
setup.py:377: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  log.warn(ex)
WARNING:setup.py:command 'C:\\Users\\User\\msys64\\mingw64\\bin/x86_64-w64-mingw32-gcc.exe' failed with exit status 1
setup.py:378: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  log.warn(BUILD_EXT_WARNING)
WARNING:setup.py:The C extension could not be compiled, speedups are not enabled.
setup.py:379: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  log.warn("Failure information, if any, is above.")
WARNING:setup.py:Failure information, if any, is above.
setup.py:380: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  log.warn("I'm retrying the build without the C extension now.")
WARNING:setup.py:I'm retrying the build without the C extension now.
running install
running build
running build_py

creating build/lib
creating build/lib/shapely
copying shapely/affinity.py -> build/lib/shapely
copying shapely/coords.py -> build/lib/shapely
copying shapely/ctypes_declarations.py -> build/lib/shapely
copying shapely/errors.py -> build/lib/shapely
copying shapely/ftools.py -> build/lib/shapely
copying shapely/geos.py -> build/lib/shapely
copying shapely/impl.py -> build/lib/shapely
copying shapely/iterops.py -> build/lib/shapely
copying shapely/linref.py -> build/lib/shapely
copying shapely/ops.py -> build/lib/shapely
copying shapely/predicates.py -> build/lib/shapely
copying shapely/prepared.py -> build/lib/shapely
copying shapely/strtree.py -> build/lib/shapely
copying shapely/topology.py -> build/lib/shapely
copying shapely/validation.py -> build/lib/shapely
copying shapely/wkb.py -> build/lib/shapely
copying shapely/wkt.py -> build/lib/shapely
copying shapely/_buildcfg.py -> build/lib/shapely
copying shapely/__init__.py -> build/lib/shapely
creating build/lib/shapely/geometry
copying shapely/geometry/base.py -> build/lib/shapely/geometry
copying shapely/geometry/collection.py -> build/lib/shapely/geometry
copying shapely/geometry/geo.py -> build/lib/shapely/geometry
copying shapely/geometry/linestring.py -> build/lib/shapely/geometry
copying shapely/geometry/multilinestring.py -> build/lib/shapely/geometry
copying shapely/geometry/multipoint.py -> build/lib/shapely/geometry
copying shapely/geometry/multipolygon.py -> build/lib/shapely/geometry
copying shapely/geometry/point.py -> build/lib/shapely/geometry
copying shapely/geometry/polygon.py -> build/lib/shapely/geometry
copying shapely/geometry/proxy.py -> build/lib/shapely/geometry
copying shapely/geometry/__init__.py -> build/lib/shapely/geometry
creating build/lib/shapely/algorithms
copying shapely/algorithms/cga.py -> build/lib/shapely/algorithms
copying shapely/algorithms/polylabel.py -> build/lib/shapely/algorithms
copying shapely/algorithms/__init__.py -> build/lib/shapely/algorithms
creating build/lib/shapely/examples
copying shapely/examples/dissolve.py -> build/lib/shapely/examples
copying shapely/examples/geoms.py -> build/lib/shapely/examples
copying shapely/examples/intersect.py -> build/lib/shapely/examples
copying shapely/examples/__init__.py -> build/lib/shapely/examples
creating build/lib/shapely/speedups
copying shapely/speedups/__init__.py -> build/lib/shapely/speedups
creating build/lib/shapely/vectorized
copying shapely/vectorized/__init__.py -> build/lib/shapely/vectorized
running install_lib
copying build/lib/shapely/geos.py -> C:/Users/User/msys64/mingw64/lib/python3.7/site-packages/shapely
copying build/lib/shapely/_buildcfg.py -> C:/Users/User/msys64/mingw64/lib/python3.7/site-packages/shapely
byte-compiling C:/Users/User/msys64/mingw64/lib/python3.7/site-packages/shapely/geos.py to geos.cpython-37.pyc
byte-compiling C:/Users/User/msys64/mingw64/lib/python3.7/site-packages/shapely/_buildcfg.py to _buildcfg.cpython-37.pyc
running install_egg_info
Removing C:/Users/User/msys64/mingw64/lib/python3.7/site-packages/Shapely-1.6.4.post2-py3.7.egg-info
Writing C:/Users/User/msys64/mingw64/lib/python3.7/site-packages/Shapely-1.6.4.post2-py3.7.egg-info
setup.py:391: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  log.warn(BUILD_EXT_WARNING)
WARNING:setup.py:The C extension could not be compiled, speedups are not enabled.
```

**Comment by snorfalorpagus** [comment]
@schelmo What does geos-config return? i.e. what are the CFLAGS and LDFLAGS from your command below?

```
$ CFLAGS="$(/mingw64/bin/geos-config --cflags)" LDFLAGS="$(/mingw64/bin/geos-config --clibs)" python3 setup.py install
```

**Comment by victorliu** [comment]
I managed to get shapely installed in python2 with pip, but I can't import shapely.geometry due to the geos DLL being named libgeos_c.dll. I modified the load_dll call ([geos.py](https://github.com/Toblerity/Shapely/blob/master/shapely/geos.py#L142) to add libgeos_c.dll as a fallback.

**Comment by sgillies** [comment]
Closing. The underlying problems are going away in 2.0.
