### ISSUE TITLE
pyinstaller issue with shapely while execution

### ISSUE THREAD

**Issue by sanj0212** [Toblerity/Shapely#662]
Hi
I am getting below issue while running the pyinstllaer created exe of the python script (containing shapely.geometry module).  Kindly help to understand and resolve.
--------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "import_die_exe.py", line 8, in <module>
  File "/tmp/pip-build-oVEsEZ/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "Shapely-1.6.4.post1-py2.7-linux-x86_64.egg/shapely/geometry/__init__.py", line 4, in <module>
  File "/tmp/pip-build-oVEsEZ/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "Shapely-1.6.4.post1-py2.7-linux-x86_64.egg/shapely/geometry/base.py", line 17, in <module>
  File "/tmp/pip-build-oVEsEZ/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "Shapely-1.6.4.post1-py2.7-linux-x86_64.egg/shapely/coords.py", line 8, in <module>
  File "/tmp/pip-build-oVEsEZ/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "Shapely-1.6.4.post1-py2.7-linux-x86_64.egg/shapely/geos.py", line 178, in <module>
  File "Shapely-1.6.4.post1-py2.7-linux-x86_64.egg/shapely/geos.py", line 166, in _geos_version
AttributeError: 'NoneType' object has no attribute 'GEOSversion'
[3202] Failed to execute script import_die_exe

**Comment by sgillies** [comment]
I have a feeling that since Shapely is not a pure Python module and requires a shared library, it will never fully work with pyinstaller on all possible platforms in the way that pyinstaller users expect. I suggest checking in https://github.com/Toblerity/Shapely/search?q=pyinstaller&type=Issues for related issues and asking on a pyinstaller support forum for advice.

**Comment by flutefreak7** [comment]
Definitely you need to bring this up in the pyinstaller issue tracker since they are very devoted to getting packages like Shapely working well. PyInstaller has a shapely-specific hook that it uses to locate the dll/lib files depending on the platform and type of installation.

PyInstaller has those hooks for hundreds of libraries, many of which have much more complicated structure than just a couple shared libraries - like PyQt5 for example.
