### ISSUE TITLE
Can shapely be expected to work on PyPy?

### ISSUE THREAD

**Issue by deeplook** [Toblerity/Shapely#687]
## Expected behavior and actual behavior.

I can install shapely fine, but when I try to use it, I'm getting an error saying it cannot find `libgeos`. Should this be installed by `pip3 install shapely` or should it be available before? If it is will it be picked up by `shapely`?

## Steps to reproduce the problem.

```bash
$ pypy3.6-v7.0.0-osx64/bin/pip3 install shapely
Collecting shapely
  Downloading https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz (225kB)
    100% |████████████████████████████████| 235kB 2.8MB/s
Building wheels for collected packages: shapely
  Building wheel for shapely (setup.py) ... done
  Stored in directory: /Users/gherman/Library/Caches/pip/wheels/f3/d8/d1/c67ff2ac7048cf6956121353de156b56f8d291b88e2a0e699b
Successfully built shapely
Installing collected packages: shapely
Successfully installed shapely-1.6.4.post2


$ pypy3.6-v7.0.0-osx64/bin/pypy3
Python 3.6.1 (dab365a46514, Feb 05 2019, 18:05:11)
[PyPy 7.0.0-alpha0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
And now for something completely different: ``forward compatibility with
optimizations that haven't been invented yet''
>>>> import shapely
>>>> from shapely.geometry import Point
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/pypy3.6-v7.0.0-osx64/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "[...]/pypy3.6-v7.0.0-osx64/site-packages/shapely/geometry/base.py", line 17, in <module>
    from shapely.coords import CoordinateSequence
  File "[...]/pypy3.6-v7.0.0-osx64/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "[...]/pypy3.6-v7.0.0-osx64/site-packages/shapely/geos.py", line 111, in <module>
    _lgeos = load_dll('geos_c', fallbacks=alt_paths)
  File "[...]/pypy3.6-v7.0.0-osx64/site-packages/shapely/geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib geos_c or load any of its variants ['[...]/pypy3.6-v7.0.0-osx64/lib/libgeos_c.dylib', '/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib'].
```

## Operating system

Mac OS X 10.14

## Shapely version and provenance

1.6.4.post2 installed from PyPI using pip

**Comment by sgillies** [comment]
Yes, you'll need to acquire and install the GEOS library separately. Then when you pip install shapely, set the GEOS_CONFIG environment variable to the location of your new geos-config executable: `GEOS_CONFIG=path/to/geos-config pip install --no-binary shapely shapely`.
