### ISSUE TITLE
AttributeError: 'list' object has no attribute '__array_interface__' (while creating a Polygon)

### ISSUE THREAD

**Issue by nbro** [Toblerity/Shapely#751]
## Expected behavior and actual behavior.

I am getting the following error:

```
Traceback (most recent call last):
  File "shapely\speedups\_speedups.pyx", line 234, in shapely.speedups._speedups.geos_linearring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/path_to_file/my_file.py", line 23, in <module>
    compute_polygons(coordinates)
  File "C:/path_to_file/my_file.py", line 12, in compute_polygons
    first["right"][:-1]]))
  File "C:\path\venv\lib\site-packages\shapely\geometry\polygon.py", line 240, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "C:\path\venv\lib\site-packages\shapely\geometry\polygon.py", line 494, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely\speedups\_speedups.pyx", line 323, in shapely.speedups._speedups.geos_linearring_from_py
AssertionError

```

Expected behaviour: no error and the polygon is constructed correctly.

## Steps to reproduce the problem.

```
import logging
from shapely.geometry import Polygon


def compute_polygons(coordinates: list) -> list:
    polygons = []
    for first, second in zip(coordinates, coordinates[1:]):
        logging.debug(first, second)
        polygons.append(Polygon([first["left"][:-1],
                                 second["left"][:-1],
                                 second["right"][:-1],
                                 first["right"][:-1]]))
    return polygons


if __name__ == "__main__":
    coordinates = [{'left': [-3.108583845827884, -2.517281564199349],
                    'middle': [0, 0, -28, 8],
                    'right': [3.108583845827884, 2.517281564199349]},
                   {'left': [-32.68664222517024, 34.008578624278286],
                    'middle': [-29.57805837934235, 36.52586018847764, -28, 8],
                    'right': [-26.469474533514468, 39.04314175267699]}]
    compute_polygons(coordinates)
```

## Operating system

Windows 10.

## Shapely version and provenance

```
Shapely           1.6.4.post1
pip 19.0.3 
python 3.6
```

**Comment by nbro** [comment]
The problem was that I was using `first["left"][:-1]` rather than `first["left"][:2]`.

**Comment by amenk** [comment]
@nbro Is this related to https://github.com/Zverik/regional/issues/5 ?
