### ISSUE TITLE
Shapely not looking in system paths for geos library

### ISSUE THREAD

**Issue by AgilentGCMS** [Toblerity/Shapely#796]
## Background
I installed libgeos and proj libraries in custom locations on a Mac, because I don't have admin privileges on that computer. I then installed shapely with the following:
```
export CFLAGS='-I/Users/sbasu1/packages/include -I/Users/sbasu1/packages/macports/include'
export LDFLAGS='-I/Users/sbasu1/packages/lib -I/Users/sbasu1/packages/macports/lib'
pip3 install --no-binary shapely shapely
```
The last step was to ensure that shapely would find the libraries in custom locations. The install finished without error.

## Expected behavior and actual behavior.
When I try to import shapely.geometry, this happens:
```
In [2]: import shapely.geometry
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-62e74f53568a> in <module>
----> 1 import shapely.geometry

~/packages/python3/lib/python3.8/site-packages/shapely/geometry/__init__.py in <module>
      2 """
      3
----> 4 from .base import CAP_STYLE, JOIN_STYLE
      5 from .geo import box, shape, asShape, mapping
      6 from .point import Point, asPoint

~/packages/python3/lib/python3.8/site-packages/shapely/geometry/base.py in <module>
     15
     16 from shapely.affinity import affine_transform
---> 17 from shapely.coords import CoordinateSequence
     18 from shapely.errors import WKBReadingError, WKTReadingError
     19 from shapely.ftools import wraps

~/packages/python3/lib/python3.8/site-packages/shapely/coords.py in <module>
      6 from ctypes import byref, c_double, c_uint
      7
----> 8 from shapely.geos import lgeos
      9 from shapely.topology import Validating
     10

~/packages/python3/lib/python3.8/site-packages/shapely/geos.py in <module>
    109                 '/opt/local/lib/libgeos_c.dylib',
    110             ]
--> 111         _lgeos = load_dll('geos_c', fallbacks=alt_paths)
    112
    113     free = load_dll('c').free

~/packages/python3/lib/python3.8/site-packages/shapely/geos.py in load_dll(libname, fallbacks, mode)
     52     else:
     53         # No shared library was loaded. Raise OSError.
---> 54         raise OSError(
     55             "Could not find lib {0} or load any of its variants {1}.".format(
     56                 libname, fallbacks or []))

OSError: Could not find lib geos_c or load any of its variants ['/Users/sbasu1/packages/python3/lib/libgeos_c.dylib', '/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib'].
```
`libgeos_c.dylib` is present in my system, and in a path included in `LD_LIBRARY_PATH`.
```
$ ls -l /Users/sbasu1/packages/macports/lib/libgeos_c.*
-rwxr-xr-x 1 sbasu1 staff 210136 2019 Oct 30 14:14:14 /Users/sbasu1/packages/macports/lib/libgeos_c.1.dylib
-rw-r--r-- 1 sbasu1 staff 283640 2019 Oct 30 14:14:14 /Users/sbasu1/packages/macports/lib/libgeos_c.a
lrwxr-xr-x 1 sbasu1 staff     17 2019 Oct 30 14:14:14 /Users/sbasu1/packages/macports/lib/libgeos_c.dylib -> libgeos_c.1.dylib
$ echo $LD_LIBRARY_PATH
/Users/sbasu1/packages/openssl/lib:/Users/sbasu1/packages/lib:/Users/sbasu1/packages/macports/lib:
```
However, shapely looks in a set of predefined paths and not in the components of `LD_LIBRARY_PATH`, which is broken behavior, IMO. I could change the `alt_paths` list in `site-packages/shapely/geos.py` short-term, but that would get overwritten with any update. So how do I fix this long term?
## Operating system

Macos 10.14.6

## Shapely version and provenance

1.6.4.post2 installed with `pip3 install --no-binary shapely shapely`.

**Comment by jorisvandenbossche** [comment]
@AgilentGCMS See https://github.com/Toblerity/Shapely#source-distributions, you should be able to specify a `GEOS_CONFIG` environment variable

**Comment by sgillies** [comment]
Yes, setting GEOS_CONFIG is the best option. Also, it is quite common that `pip` or `pip3`, for various reasons, doesn't resolve in the way one expects, so I recommend this:

`GEOS_CONFIG=Users/sbasu1/packages/macports/bin/gdal-config python3 -m pip install --no-binary shapely shapely`

**Comment by AgilentGCMS** [comment]
> Yes, setting GEOS_CONFIG is the best option. Also, it is quite common that `pip` or `pip3`, for various reasons, doesn't resolve in the way one expects, so I recommend this:
> 
> `GEOS_CONFIG=Users/sbasu1/packages/macports/bin/gdal-config python3 -m pip install --no-binary shapely shapely`

Just tried what was suggested, except that I don't have gdal-config, I have geos-config. So I installed with

```
$ GEOS_CONFIG=~/packages/macports/bin/geos-config python3 -m pip install --no-binary shapely shapely
Collecting shapely
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
Installing collected packages: shapely
    Running setup.py install for shapely ... done
Successfully installed shapely-1.6.4.post2
```

However, importing shapely still raises an error:

```
In [1]: import shapely.geometry
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-62e74f53568a> in <module>
----> 1 import shapely.geometry

~/packages/python3/lib/python3.8/site-packages/shapely/geometry/__init__.py in <module>
      2 """
      3
----> 4 from .base import CAP_STYLE, JOIN_STYLE
      5 from .geo import box, shape, asShape, mapping
      6 from .point import Point, asPoint

~/packages/python3/lib/python3.8/site-packages/shapely/geometry/base.py in <module>
     15
     16 from shapely.affinity import affine_transform
---> 17 from shapely.coords import CoordinateSequence
     18 from shapely.errors import WKBReadingError, WKTReadingError
     19 from shapely.ftools import wraps

~/packages/python3/lib/python3.8/site-packages/shapely/coords.py in <module>
      6 from ctypes import byref, c_double, c_uint
      7
----> 8 from shapely.geos import lgeos
      9 from shapely.topology import Validating
     10

~/packages/python3/lib/python3.8/site-packages/shapely/geos.py in <module>
    109                 '/opt/local/lib/libgeos_c.dylib',
    110             ]
--> 111         _lgeos = load_dll('geos_c', fallbacks=alt_paths)
    112
    113     free = load_dll('c').free

~/packages/python3/lib/python3.8/site-packages/shapely/geos.py in load_dll(libname, fallbacks, mode)
     52     else:
     53         # No shared library was loaded. Raise OSError.
---> 54         raise OSError(
     55             "Could not find lib {0} or load any of its variants {1}.".format(
     56                 libname, fallbacks or []))

OSError: Could not find lib geos_c or load any of its variants ['/Users/sbasu1/packages/python3/lib/libgeos_c.dylib', '/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib'].
```
i.e., it's still not looking in the right place for libgeos_c.dylib, which exists:
```
$ ls -l /Users/sbasu1/packages/macports/lib/libgeos*
-rwxr-xr-x 1 sbasu1 staff 1389840 2019 Oct 30 14:14:13 /Users/sbasu1/packages/macports/lib/libgeos-3.8.0.dylib
-rw-r--r-- 1 sbasu1 staff 3993648 2019 Oct 30 14:14:14 /Users/sbasu1/packages/macports/lib/libgeos.a
lrwxr-xr-x 1 sbasu1 staff      19 2019 Oct 30 14:14:13 /Users/sbasu1/packages/macports/lib/libgeos.dylib -> libgeos-3.8.0.dylib
-rwxr-xr-x 1 sbasu1 staff  210136 2019 Oct 30 14:14:14 /Users/sbasu1/packages/macports/lib/libgeos_c.1.dylib
-rw-r--r-- 1 sbasu1 staff  283640 2019 Oct 30 14:14:14 /Users/sbasu1/packages/macports/lib/libgeos_c.a
lrwxr-xr-x 1 sbasu1 staff      17 2019 Oct 30 14:14:14 /Users/sbasu1/packages/macports/lib/libgeos_c.dylib -> libgeos_c.1.dylib
```

**Comment by sgillies** [comment]
@AgilentGCMS apologies, I got a little confused between the build-time and runtime issues. geos-config is the program to call upon at build time, but it doesn't eliminate the need to set `DYLD_LIBRARY_PATH` (to `/Users/sbasu1/packages/macports/lib` in your case) so that shapely can dlopen the GEOS .dylib.

**Comment by AgilentGCMS** [comment]
Ah, I'm new to macs, so didn't know that I needed DYLD_LIBRARY_PATH, not LD_LIBRARY_PATH. However, setting `DYLD_LIBRARY_PATH` to include `/Users/sbasu1/packages/macports/lib` has the unintended consequence that I can no longer start ipython:

```
$ ipython
Traceback (most recent call last):
  File "/Users/sbasu1/packages/python3/bin/ipython", line 5, in <module>
    from IPython import start_ipython
  File "/Users/sbasu1/packages/python3/lib/python3.8/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/Users/sbasu1/packages/python3/lib/python3.8/site-packages/IPython/terminal/embed.py", line 17, in <module>
    from IPython.terminal.ipapp import load_default_config
  File "/Users/sbasu1/packages/python3/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 28, in <module>
    from IPython.core.magics import (
  File "/Users/sbasu1/packages/python3/lib/python3.8/site-packages/IPython/core/magics/__init__.py", line 18, in <module>
    from .code import CodeMagics, MacroToEdit
  File "/Users/sbasu1/packages/python3/lib/python3.8/site-packages/IPython/core/magics/code.py", line 23, in <module>
    from urllib.request import urlopen
  File "/Users/sbasu1/packages/python3/lib/python3.8/urllib/request.py", line 2584, in <module>
    from _scproxy import _get_proxy_settings, _get_proxies
ImportError: dlopen(/Users/sbasu1/packages/python3/lib/python3.8/lib-dynload/_scproxy.cpython-38-darwin.so, 2): Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Users/sbasu1/packages/macports/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```
Basically, the ipython I'm using is not from macports, it's installed in `/Users/sbasu1/packages/python3/bin/ipython`. I installed that python tree before I even installed macports, so it linked to system libraries where appropriate. Now however there seems to be a conflict between system libraries and macports. 

Is there no way for shapely to just look in LD_LIBRARY_PATH instead of DYLD_LIBRARY_PATH?

**Comment by sgillies** [comment]
@AgilentGCMS according to https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html LD_LIBRARY_PATH should work as well. I'm going to close this issue now. The problem you're having with macports and ipython is out of my control.

**Comment by AgilentGCMS** [comment]
But it does *not* work to have libgeos_c.dylib in LD_LIBRARY_PATH, that's the entire problem. If it did, none of this conflict between macports and ipython would matter.

```
$ echo $LD_LIBRARY_PATH
/Users/sbasu1/packages/openssl/lib:/Users/sbasu1/packages/lib:/Users/sbasu1/packages/macports/lib
$ ls -l /Users/sbasu1/packages/macports/lib/libgeos*.dylib
-rwxr-xr-x 1 sbasu1 staff 1389840 2019 Oct 30 14:14:13 /Users/sbasu1/packages/macports/lib/libgeos-3.8.0.dylib
lrwxr-xr-x 1 sbasu1 staff      19 2019 Oct 30 14:14:13 /Users/sbasu1/packages/macports/lib/libgeos.dylib -> libgeos-3.8.0.dylib
-rwxr-xr-x 1 sbasu1 staff  210136 2019 Oct 30 14:14:14 /Users/sbasu1/packages/macports/lib/libgeos_c.1.dylib
lrwxr-xr-x 1 sbasu1 staff      17 2019 Oct 30 14:14:14 /Users/sbasu1/packages/macports/lib/libgeos_c.dylib -> libgeos_c.1.dylib
```

However, if you look at the error I get trying to import shapely,

```
In [1]: import shapely.geometry
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-62e74f53568a> in <module>
----> 1 import shapely.geometry

~/packages/python3/lib/python3.8/site-packages/shapely/geometry/__init__.py in <module>
      2 """
      3
----> 4 from .base import CAP_STYLE, JOIN_STYLE
      5 from .geo import box, shape, asShape, mapping
      6 from .point import Point, asPoint

~/packages/python3/lib/python3.8/site-packages/shapely/geometry/base.py in <module>
     15
     16 from shapely.affinity import affine_transform
---> 17 from shapely.coords import CoordinateSequence
     18 from shapely.errors import WKBReadingError, WKTReadingError
     19 from shapely.ftools import wraps

~/packages/python3/lib/python3.8/site-packages/shapely/coords.py in <module>
      6 from ctypes import byref, c_double, c_uint
      7
----> 8 from shapely.geos import lgeos
      9 from shapely.topology import Validating
     10

~/packages/python3/lib/python3.8/site-packages/shapely/geos.py in <module>
    109                 '/opt/local/lib/libgeos_c.dylib',
    110             ]
--> 111         _lgeos = load_dll('geos_c', fallbacks=alt_paths)
    112
    113     free = load_dll('c').free

~/packages/python3/lib/python3.8/site-packages/shapely/geos.py in load_dll(libname, fallbacks, mode)
     52     else:
     53         # No shared library was loaded. Raise OSError.
---> 54         raise OSError(
     55             "Could not find lib {0} or load any of its variants {1}.".format(
     56                 libname, fallbacks or []))

OSError: Could not find lib geos_c or load any of its variants ['/Users/sbasu1/packages/python3/lib/libgeos_c.dylib', '/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib'].
```

the error makes it very clear that *none* of the paths in LD_LIBRARY_PATH are being searched!
