### ISSUE TITLE
Aws Chalice Packaging problem

### ISSUE THREAD

**Issue by msaraac** [Toblerity/Shapely#809]
## Please note

I'm using aws chalice and the requirements could not be installed

```
$ chalice package packaged/
Creating deployment package.
Traceback (most recent call last):
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\chalice\cli\__init__.py", line 512, in main
    return cli(obj={})
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\chalice\cli\__init__.py", line 441, in package
    packager.package_app(config, out, stage)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\chalice\package.py", line 919, in package_app
    config, chalice_stage_name)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\chalice\package.py", line 82, in construct_resources
    self._build_stage.execute(config, resources)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\chalice\deploy\deployer.py", line 995, in execute
    step.handle(config, resource)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\chalice\deploy\deployer.py", line 851, in handle
    handler(config, resource)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\chalice\deploy\deployer.py", line 878, in handle_deploymentpackage
    config.project_dir, config.lambda_python_version)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\chalice\deploy\packager.py", line 94, in create_deployment_package
    abi, requirements_filepath, site_packages_dir)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\chalice\deploy\packager.py", line 506, in build_site_packages
    abi, tempdir, requirements_filepath)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\chalice\deploy\packager.py", line 369, in _download_dependencies
    requirements_filename, directory)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\chalice\deploy\packager.py", line 327, in _download_all_dependencies
    self._pip.download_all_dependencies(requirements_filename, directory)
  File "c:\users\cybord\appdata\local\programs\python\python37-32\lib\site-packages\chalice\deploy\packager.py", line 739, in download_all_dependencies
    error = err.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 1397: invalid start byte

```

## Expected behavior and actual behavior.

The installatino should perform without any errors

## Steps to reproduce the problem.

-

## Operating system

Tried On Both Mac OS X & Windows

## Shapely version and provenance
shapely==1.6.4.post2

**Comment by sgillies** [comment]
The error is from chalice, not from shapely. See https://github.com/aws/chalice/blob/master/chalice/deploy/packager.py#L767. I recommend catching that exception and inspecting `err` to find the problem.

This ticket may be relevant: https://github.com/aws/chalice/issues/1285.
