### ISSUE TITLE
Error when importing geos in MacOSX: libc does not exists 

### ISSUE THREAD

**Issue by pradal** [Toblerity/Shapely#888]
NB: the issue have been reported first as a conda-forge [issue](https://github.com/conda-forge/shapely-feedstock/issues/64). 
The error can be reproduced either on anaconda, conda or pip. 

## Expected behavior and actual behavior.

`from shapely import geos` fail.
The error is:

```Traceback (most recent call last): 
    File "<stdin>", line 1, in <module> 
    File "/Users/pradal/miniconda3/envs/shapeely/lib/python3.8/site-packages/shapely/geos.py", line 113, in <module> 
        free = load_dll('c').free 
    File "/Users/pradal/miniconda3/envs/shapeely/lib/python3.8/site-packages/shapely/geos.py", line 54, in load_dll 
        raise OSError( 
OSError: Could not find lib c or load any of its variants [].
```

## Steps to reproduce the problem.
`from shapely import geos`

Everything works if I change (in geos.py, line 113)

`free = load_dll('c').free`

by

1. `free = load_dll('System').free`
or
2. `free = load_dll('cxx').free` (
or even
3. `free=CDLL(None).free

See issue [64 on shapely-feedstock](https://github.com/conda-forge/shapely-feedstock/issues/64). 
> `libc` equivalent of macOS is `libSystem`, so `load_dll('c')` doesn't work.
> This is an issue upstream and not a packaging issue.

## Operating system

Mac OS X 10.15.1
No homebrew or macport installed.

## Shapely version and provenance

1.7.0

**Comment by sgillies** [comment]
We are testing on Mac OS X, but only version 10.13: https://travis-ci.com/github/shapely/shapely-wheels/jobs/292629466. Thanks for suggesting `CDLL(None)`, that seems like an approach that would work across platforms.

**Comment by pradal** [comment]
Do you want a PR?

**Comment by sgillies** [comment]
@pradal sure, if you've got the time and interest! Can you aim the PR at our maint-1.7 branch?

**Comment by pradal** [comment]
I have made the modification  in the PR #891  only for darwin, because I can not test other systems.
But it can easily generalised on other *nix systems.

**Comment by ambientlight** [comment]
@sgillies: This issue still exist in `1.7.0`, as I missing something?

**Comment by sgillies** [comment]
@ambientlight the fix is in the 1.7 branch but we haven't yet made a release that has the fix. Sorry about that.

**Comment by camden-lowrance** [comment]
`free = CDLL(None).free` works for me on BigSur 11.1 in a conda environment and Shapely 1.6.4

**Comment by brianckeegan** [comment]
Not sure why this is closed. Same error on a fresh install of Anaconda 05.2021 on OS X 10.16.

conda info:
```
active environment : base
    active env location : /Users/briankeegan/opt/anaconda3
            shell level : 1
       user config file : /Users/briankeegan/.condarc
 populated config files : /Users/briankeegan/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.10.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/briankeegan/opt/anaconda3  (writable)
      conda av data dir : /Users/briankeegan/opt/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/briankeegan/opt/anaconda3/pkgs
                          /Users/briankeegan/.conda/pkgs
       envs directories : /Users/briankeegan/opt/anaconda3/envs
                          /Users/briankeegan/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.10 Darwin/20.4.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```


import geopandas as gpd:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/briankeegan/opt/anaconda3/lib/python3.8/site-packages/geopandas/__init__.py", line 1, in <module>
    from geopandas.geoseries import GeoSeries  # noqa
  File "/Users/briankeegan/opt/anaconda3/lib/python3.8/site-packages/geopandas/geoseries.py", line 12, in <module>
    from shapely.geometry.base import BaseGeometry
  File "/Users/briankeegan/opt/anaconda3/lib/python3.8/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Users/briankeegan/opt/anaconda3/lib/python3.8/site-packages/shapely/geometry/base.py", line 17, in <module>
    from shapely.coords import CoordinateSequence
  File "/Users/briankeegan/opt/anaconda3/lib/python3.8/site-packages/shapely/coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "/Users/briankeegan/opt/anaconda3/lib/python3.8/site-packages/shapely/geos.py", line 113, in <module>
    free = load_dll('c').free
  File "/Users/briankeegan/opt/anaconda3/lib/python3.8/site-packages/shapely/geos.py", line 54, in load_dll
    raise OSError(
OSError: Could not find lib c or load any of its variants [].
```

**Comment by fperez** [comment]
@brianckeegan fwiw, I'm not getting the same error on my conda build... Below is my conda info on two machines that are fairly similarly configured, but the first (blanca) is a 10.15 one, while the 2nd (alpamayo) is running 10.16. The only other big difference I spot is that I have conda-forge as my base default. You might check making a fresh environment with conda-forge as its default in case that's what's triggering the problem.

Sorry not to be of more help, these things can be really frustrating... When I'm stuck with one of these, my approach is just nuke-and-rebuild, for which I have a script that redoes my conda setup without much manual intervention. Blunt instrument, but gets the job done :)

OSX 10.15 (Catalina) build:
```
(base) blanca[~]> conda info

     active environment : base
    active env location : /Users/fperez/local/conda
            shell level : 1
       user config file : /Users/fperez/.condarc
 populated config files : /Users/fperez/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.8.8.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/fperez/local/conda  (writable)
      conda av data dir : /Users/fperez/local/conda/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/fperez/local/conda/pkgs
                          /Users/fperez/.conda/pkgs
       envs directories : /Users/fperez/local/conda/envs
                          /Users/fperez/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 33212:20665
             netrc file : None
           offline mode : False
```


OSX 10.16 (BigSur) build:
```
(base) alpamayo[~]> conda info

     active environment : base
    active env location : /Users/fperez/local/conda
            shell level : 1
       user config file : /Users/fperez/.condarc
 populated config files : /Users/fperez/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.8.8.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/fperez/local/conda  (writable)
      conda av data dir : /Users/fperez/local/conda/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/fperez/local/conda/pkgs
                          /Users/fperez/.conda/pkgs
       envs directories : /Users/fperez/local/conda/envs
                          /Users/fperez/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Darwin/20.4.0 OSX/10.16
                UID:GID : 33212:20665
             netrc file : None
           offline mode : False
```

**Comment by brianckeegan** [comment]
Following up on @fperez, I nuked Anaconda Individual, installed miniconda, set conda-forge to be the high priority channel, installed geopandas, and no error. So root cause seems to be something in the default Anaconda channel.
