### ISSUE TITLE
install failure on 1.7.0

### ISSUE THREAD

**Issue by dazza-codes** [Toblerity/Shapely#907]
Should the install just-work with bundled wheels?  (Maybe this is only an issue on an alpine docker image install, see below.)

```
 [EnvCommandError]
 Command ['/builds/xxx/xxx/.venv/bin/pip', 'install', '--no-deps', 'shapely==1.7.0'] errored with the following return code 1, and output: 
 Collecting shapely==1.7.0
   Downloading Shapely-1.7.0.tar.gz (349 kB)
     ERROR: Command errored out with exit status 1:
      command: /builds/xxx/xxx/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-o_o_c3zh/shapely/setup.py'"'"'; __file__='"'"'/tmp/pip-install-o_o_c3zh/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1v8vsj7v
          cwd: /tmp/pip-install-o_o_c3zh/shapely/
     Complete output (11 lines):
     Failed `CDLL(libgeos_c.so.1)`
     Failed `CDLL(libgeos_c.so)`
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-install-o_o_c3zh/shapely/setup.py", line 85, in <module>
         from shapely._buildcfg import geos_version_string, geos_version, \
       File "/tmp/pip-install-o_o_c3zh/shapely/shapely/_buildcfg.py", line 170, in <module>
         fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
       File "/tmp/pip-install-o_o_c3zh/shapely/shapely/_buildcfg.py", line 164, in load_dll
         libname, fallbacks or []))
     OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
     ----------------------------------------
```

This is getting installed on a gitlab-CI using a docker-python3.6 image:
```
# https://github.com/dazza-codes/docker-python
# https://hub.docker.com/r/dazzacodes/docker-python
# provides a base image using docker:19.03 with python 3.6;
# the docker:19.03 image is based on alpine:3.11
image: dazzacodes/docker-python:3.6
```

**Comment by jorisvandenbossche** [comment]
@dazza-codes you are not installing a wheel, but it's actually building from source ("Downloading Shapely-1.7.0.tar.gz").

This is because you are using a docker image based on alpine linux, for which there are no wheels (the manylinux wheels are not compatible with alpine)

Since you are installing from source, you need to ensure that GEOS is already installed.
