### ISSUE TITLE
Issue importing shapely.geos

### ISSUE THREAD

**Issue by chhassin** [Toblerity/Shapely#943]
Hello, 

I installed Shapely v1.7.0 from PyPI using PIP and am getting an error message related to geos. My operating system is Windows 10 Enterprise x64.

import shapely.geos
Traceback (most recent call last):

  File "<ipython-input-23-80e4b52d4876>", line 1, in <module>
    import shapely.geos

  File "C:\Users\hassincd\AppData\Local\Continuum\anaconda3\lib\site-packages\shapely\geos.py", line 145, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))

  File "C:\Users\hassincd\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 126] The specified module could not be found

Is this a geos version issue? Any help is much appreciated!

**Comment by sgillies** [comment]
@chhassin anaconda users must get shapely using conda, not pip. `conda install shapely -c conda-forge`.

https://anaconda.org/conda-forge/shapely/

**Comment by chhassin** [comment]
@sgillies , thank you, this fixed it
