### ISSUE TITLE
Topology Exception in valid polygon

### ISSUE THREAD

**Issue by aydal** [Toblerity/Shapely#957]
I have a list of geometries in GeoPandas, which consist of Polygon and LineString. I am trying to convert LineString to Polygon using buffer because I need to use it in voronoi_diagram. 

```
>>> c =LineString([(8601635.012337072, 2653275.483739082), (8601667.851586856, 2653238.721249395), (8601712.602022154, 2653208.9497218933), (8601871.454935515, 2653149.6478985697), (8602007.376033774, 2653084.3197241016), (8602027.079583647, 2653067.9274569103), (8602037.54361578, 2653052.4994562212), (8602045.224660644, 2653037.0714705535), (8602060.475430883, 2653025.2594291777), (8602152.75928875, 2652992.5955646853), (8602240.813005969, 2652973.55171904), (8602268.308920195, 2652980.0603725724), (8602412.24502179, 2652995.4883027347), (8602467.125530751, 2652987.171682267), (8602620.301150084, 2653000.5505955922), (8602653.140399868, 2653031.165448764), (8602800.304766696, 2653050.691488374), (8602943.684270838, 2653053.1021122164), (8602988.76866461, 2653051.0530819274), (8603045.875563387, 2653043.5801501744), (8603088.176969886, 2653036.830408397), (8603188.25319211, 2653013.6884584087), (8603241.68654769, 2652994.0419336436), (8603286.436982991, 2652970.2973932764), (8603308.144283695, 2652952.5794091793), (8603342.653325839, 2652941.7316735894), (8603396.643278876, 2652906.777909426), (8603411.894049115, 2652898.4613355114), (8603443.508784499, 2652895.448085172), (8603464.436848769, 2652896.65338524), (8603480.24421646, 2652907.621620064), (8603494.938389245, 2652913.8891862305), (8603652.566788208, 2652950.65092231), (8603739.7299495, 2652963.1860911557), (8603771.122045903, 2652964.6324574314), (8603810.751784626, 2652955.231079007), (8603824.555401485, 2652951.012513579), (8603843.924992882, 2652940.285309404), (8603861.290833447, 2652923.652130774), (8603972.165046277, 2652796.1316746194), (8604065.22814058, 2652689.1020649103), (8604110.31253435, 2652658.6084007607), (8604151.166787473, 2652635.346475068), (8604177.994784754, 2652620.8831187948), (8604204.377504071, 2652608.709804162), (8604235.32432251, 2652598.2238871735), (8604262.597597757, 2652589.063781458), (8604290.872748418, 2652583.7605647785), (8604322.264844822, 2652578.698405059), (8604349.983398028, 2652574.23888474), (8604369.130350444, 2652568.935673023), (8604404.641268007, 2652559.052419558), (8604446.497396547, 2652550.4949733634), (8604473.993310772, 2652544.227550915), (8604499.596793655, 2652533.862203839), (8604531.322848532, 2652531.4516589795), (8604565.943210168, 2652534.4648401113), (8604605.35030991, 2652538.5627673697), (8604628.616083486, 2652547.4817891833), (8604651.881857062, 2652549.2896996215), (8604686.279579716, 2652550.133391231), (8604716.6698007, 2652546.9996797675)])

>>> d=c.buffer(10,1,join_style=3)
>>> d.is_valid
True
>>> from shapely.ops import voronoi_diagram
>>> voronoi_diagram(d)
TopologyException: Input geom 1 is invalid: Self-intersection at or near point 8601635.01233707 2653275.483739086 at 8601635.01233707 2653275.483739086
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/shapely/ops.py", line 222, in voronoi_diagram
    result = geom_factory(func(geom._geom, envelope, tolerance, int(edges)))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/shapely/geometry/base.py", line 69, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/shapely/ops.py", line 227, in voronoi_diagram
    raise ValueError(errstr)
ValueError: Could not create Voronoi Diagram with the specified inputs.
```
buffer(0) doesn't work as well. Help is appreciated. The red dot is the point mentioned in the error
![Figure_1](https://user-images.githubusercontent.com/21153132/89640190-acaa6e80-d8cc-11ea-82d8-88cf2f0b02a0.png)
![Figure_2](https://user-images.githubusercontent.com/21153132/89640196-ae743200-d8cc-11ea-841b-9f538a77c2f8.png)

**Comment by sgillies** [comment]
@aydal I've confirmed the TopologyError. And I've found that if we make a MultiPolygon of the polygonized edges of the Voronoi Diagram that MultiPolygon is invalid.

![Untitled](https://user-images.githubusercontent.com/33697/89739032-84408280-da3a-11ea-80a6-2494c516fb01.png)

However: `polys = list(polygonize(edges))` gives a list of 140 *valid* polygons. This may be useful to you? I think it may be practically impossible to make a valid MultiPolygon from the results of voronoi_diagram due to imperfect floating point precision.

cc @tomplex

**Comment by tomplex** [comment]
> I am trying to convert LineString to Polygon using buffer because I need to use it in voronoi_diagram.

Maybe I'm misunderstanding you, but you don't *need* to pass a polygon into `voronoi_diagram`. Regardless of what geometry you pass in, the underlying GEOS algorithm is going to explode it into a point set and create a diagram from that. You can pass your LineString in directly:

```python
from shapely.ops import voronoi_diagram
from shapely.geometry import LineString

ls = LineString([(8601635.012337072, 2653275.483739082), (8601667.851586856, 2653238.721249395), (8601712.602022154, 2653208.9497218933), (8601871.454935515, 2653149.6478985697), (8602007.376033774, 2653084.3197241016), (8602027.079583647, 2653067.9274569103), (860203
7.54361578, 2653052.4994562212), (8602045.224660644, 2653037.0714705535), (8602060.475430883, 2653025.2594291777), (8602152.75928875, 2652992.5955646853), (8602240.813005969, 2652973.55171904), (8602268.308920195, 2652980.0603725724), (8602412.24502179, 2652995.4883027347
), (8602467.125530751, 2652987.171682267), (8602620.301150084, 2653000.5505955922), (8602653.140399868, 2653031.165448764), (8602800.304766696, 2653050.691488374), (8602943.684270838, 2653053.1021122164), (8602988.76866461, 2653051.0530819274), (8603045.875563387, 2653043
.5801501744), (8603088.176969886, 2653036.830408397), (8603188.25319211, 2653013.6884584087), (8603241.68654769, 2652994.0419336436), (8603286.436982991, 2652970.2973932764), (8603308.144283695, 2652952.5794091793), (8603342.653325839, 2652941.7316735894), (8603396.643278
876, 2652906.777909426), (8603411.894049115, 2652898.4613355114), (8603443.508784499, 2652895.448085172), (8603464.436848769, 2652896.65338524), (8603480.24421646, 2652907.621620064), (8603494.938389245, 2652913.8891862305), (8603652.566788208, 2652950.65092231), (8603739
.7299495, 2652963.1860911557), (8603771.122045903, 2652964.6324574314), (8603810.751784626, 2652955.231079007), (8603824.555401485, 2652951.012513579), (8603843.924992882, 2652940.285309404), (8603861.290833447, 2652923.652130774), (8603972.165046277, 2652796.1316746194),
 (8604065.22814058, 2652689.1020649103), (8604110.31253435, 2652658.6084007607), (8604151.166787473, 2652635.346475068), (8604177.994784754, 2652620.8831187948), (8604204.377504071, 2652608.709804162), (8604235.32432251, 2652598.2238871735), (8604262.597597757, 2652589.06
3781458), (8604290.872748418, 2652583.7605647785), (8604322.264844822, 2652578.698405059), (8604349.983398028, 2652574.23888474), (8604369.130350444, 2652568.935673023), (8604404.641268007, 2652559.052419558), (8604446.497396547, 2652550.4949733634), (8604473.993310772, 2
652544.227550915), (8604499.596793655, 2652533.862203839), (8604531.322848532, 2652531.4516589795), (8604565.943210168, 2652534.4648401113), (8604605.35030991, 2652538.5627673697), (8604628.616083486, 2652547.4817891833), (8604651.881857062, 2652549.2896996215), (8604686.
279579716, 2652550.133391231), (8604716.6698007, 2652546.9996797675)])
diagram = voronoi_diagram(ls)
```

<img width="601" alt="Screen Shot 2020-08-10 at 7 17 38 PM" src="https://user-images.githubusercontent.com/8109856/89840430-3ca31f00-db3e-11ea-8690-eaf3b90e2943.png">

You can also do as @sgillies did and only return edges, polygonize them and create a geometry from that:

```python
from shapely.geometry import GeometryCollection
from shapely import ops

diagram = voronoi_diagram(ls, edges=True)
collection = GeometryCollection(list(ops.polygonize(diagram)))
```

<img width="544" alt="Screen Shot 2020-08-10 at 7 41 58 PM" src="https://user-images.githubusercontent.com/8109856/89841744-c4d6f380-db41-11ea-9316-2f3d60b14942.png">


You might also wish to play around with the `tolerance` argument for `voronoi_diagram`. It will do some snapping / rounding of coordinates to try and make the algorithm more robust. the [PostGIS docs](https://postgis.net/docs/ST_VoronoiPolygons.html) have a decent description.

**Comment by aydal** [comment]
@sgillies @tomplex Thanks a lot for your help.
As for the need for a buffer to LineString they represent roads and for my application, I need to give them some width. 
Going by @sgillies approach, it may hold for individual geometries but malfunctions on a list. (Gray is the `edges=True` approach)
![Figure_1](https://user-images.githubusercontent.com/21153132/89863772-69037d80-dbc8-11ea-9163-374d4e5625f6.png)
![Figure_2](https://user-images.githubusercontent.com/21153132/89863778-6b65d780-dbc8-11ea-9b3d-c1a0cd6b870f.png)

I will look into the tolerance and see if that helps.

**Comment by jorisvandenbossche** [comment]
I think the issues can be closed? 
With the latest released versions, I also no longer get a TopologyException for the original example in the top post.
