### ISSUE TITLE
voronoi_diagram

### ISSUE THREAD

**Issue by mars0001** [Toblerity/Shapely#972]
Hi,

OS: Windows 10 x64 build 19041.450
Python 3.8.2.0

I know that this is not released yet but I know that without feedback no improvements are done (limited time etc).
It seems that using this four points multipoint:
`MULTIPOINT (20.1273 18.7303, 26.5107 18.7303, 20.1273 23.8437, 26.5107 23.8437)`
creates an issue (self-intersection) way outside of the area of interest, near point with coordinates:
` 23.319000000000003 -182.34679999999986`
(See error posted below).

I've built the wheel for Shapely 1.8.dev0 from the master branch.
It complained about missing geos_c.dll and I had to install the OSGeo4W64 package from here: https://trac.osgeo.org/osgeo4w/
Adding the OSGeo4W64/bin to the Path did not helped but copying the geos_c.dll and geos.dll to WinDIr/System32 did the trick.
While building the wheel it complained about missing geos-config script and at the end specified the speedups were not enabled and that it will look for some files when Shapely starts.

I've installed the just created Shapely 1.8.dev0 wheel and then run this script (simplified from one of yours):
**************************************
`import pytest`

`from shapely.geos import geos_version`
`from shapely.wkt import loads as load_wkt`

`from shapely.ops import voronoi_diagram`

`requires_geos_35 = pytest.mark.skipif(geos_version < (3, 5, 0), reason='GEOS >= 3.5.0 is required.')`

`@requires_geos_35`
`def test_from_multipoint_without_tolerace_with_floating_point_coordinates():`
    `mp = load_wkt('MULTIPOINT (20.1273 18.7303, 26.5107 18.7303, 20.1273 23.8437, 26.5107 23.8437)')`
    
   ` regions = voronoi_diagram(mp)`
   ` print("Len: %d -> Regions: %s" % (len(regions), str(regions)))`

`print(geos_version)`
`test_from_multipoint_without_tolerace_with_floating_point_coordinates()`

**************************************

The result when running this script:
**************************************
C:\Dev\WPy_64bit_3.8.2.0\python-3.8.2.amd64\python.exe D:/1.DEV/FlatCAM_beta/tests/test_voronoi.py
(3, 8, 1)
TopologyException: Input geom 1 is invalid: Self-intersection at or near point 23.319000000000003 -182.34679999999986 at 23.319000000000003 -182.34679999999986

Traceback (most recent call last):
  File "C:\Dev\WPy_64bit_3.8.2.0\python-3.8.2.amd64\lib\site-packages\shapely\ops.py", line 222, in voronoi_diagram
    result = geom_factory(func(geom._geom, envelope, tolerance, int(edges)))
  File "C:\Dev\WPy_64bit_3.8.2.0\python-3.8.2.amd64\lib\site-packages\shapely\geometry\base.py", line 70, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/1.DEV/FlatCAM_beta/tests/test_voronoi.py", line 26, in <module>
    test_from_multipoint_without_tolerace_with_floating_point_coordinates()
  File "D:/1.DEV/FlatCAM_beta/tests/test_voronoi.py", line 22, in test_from_multipoint_without_tolerace_with_floating_point_coordinates
    regions = voronoi_diagram(mp)
  File "C:\Dev\WPy_64bit_3.8.2.0\python-3.8.2.amd64\lib\site-packages\shapely\ops.py", line 227, in voronoi_diagram
    raise ValueError(errstr)
ValueError: Could not create Voronoi Diagram with the specified inputs.

Process finished with exit code 1
**************************************

Thank you for this great package!
Best regards,
Marius

**Comment by tomplex** [comment]
Thanks for the report, @mars0001! I was able to replicate this using shapely master branch built against GEOS 3.8.1 on MacOS. 

I was also surprised to see that this simple example - four corners of a box - doesn't work, however it also seems to fail with the same error in PostGIS:

```
postgres@localhost:postgres> SELECT
     ST_VoronoiPolygons(geom) As geom
 FROM (SELECT 'MULTIPOINT (20.1273 18.7303, 26.5107 18.7303, 20.1273 23.8437, 26.5107 23.8437)'::geometry As geom ) As g;
GEOSVoronoiDiagram: TopologyException: Input geom 1 is invalid: Self-intersection at or near point 23.319000000000003 -182.34679999999986 at 23.319000000000003 -182.34679999999986
CONTEXT:  SQL function "st_voronoipolygons" statement 1
```

So at least behavior is identical in both implementations, which are both wrapping the GEOS voronoi diagram algorithm. That said, I don't know if this is an upstream bug (incorrect behavior on the part of the algorithm) or if this is expected for this input. I'll open a ticket on the geos issue tracker to request clarification.

**Comment by tomplex** [comment]
The algorithm will succeed if you supply a quite large tolerance value - I found the boundary to be `tolarance=9`:

```python
from shapely import wkt, ops

mp = wkt.loads('MULTIPOINT (20.1273 18.7303, 26.5107 18.7303, 20.1273 23.8437, 26.5107 23.8437)')
diagram = diagram = ops.voronoi_diagram(mp, tolerance=9)
```

That yields this (unsatisfactory) result:

<img width="472" alt="Screen Shot 2020-08-23 at 8 14 37 PM" src="https://user-images.githubusercontent.com/8109856/90992405-944d7b80-e57d-11ea-8188-7e21debadc85.png">

Overall, increasing the `tolerance` argument is a good way to make the algorithm more robust if it's failing, but there's no blanket value which will make every case better; you will need to experiment with different values for every dataset.

**Comment by mars0001** [comment]
Hi,
Thank you for the answer.

I actually kind of solved my issue by iterating over the geometry (Points in MultiPoint) and if the voronoi_diagram() fails then it will do a translation of the current Point over X and Y axis by a random number between 0 and 1e-07 and try again to generate the Voronoi polygons until it works.

It looks like this way it works for me: this error is insignificant for my use case - yet-another-autolevelling for PCB (printed circuit boards) engraving.

![voronoi-4points](https://user-images.githubusercontent.com/40632281/91106681-f2608880-e67b-11ea-9cb5-c8837075ab90.PNG)

**Comment by theroggy** [comment]
This cannot be reproduced anymore with GEOS 3.14.1, so must have been fixed.
