### ISSUE TITLE
pip installing Shapely 1.7.1 on windows causing CI error

### ISSUE THREAD

**Issue by bsipocz** [Toblerity/Shapely#973]
Our CI started failing today for windows as we run into this install issue (https://travis-ci.org/github/astropy/astroquery/jobs/719798545#L2133). I'll pin the version number as a workaround for us (it's not a direct dependency for us), but this can be a real issue you may want to know about.

```
  Downloading Shapely-1.7.1.tar.gz (383 kB)

    ERROR: Command errored out with exit status 1:

     command: 'C:\tools\miniconda3\envs\test\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\travis\\AppData\\Local\\Temp\\pip-install-a6csizkd\\shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\travis\\AppData\\Local\\Temp\\pip-install-a6csizkd\\shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\travis\AppData\Local\Temp\pip-pip-egg-info-w0iz65s4'

         cwd: C:\Users\travis\AppData\Local\Temp\pip-install-a6csizkd\shapely\

    Complete output (9 lines):

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "C:\Users\travis\AppData\Local\Temp\pip-install-a6csizkd\shapely\setup.py", line 85, in <module>

        from shapely._buildcfg import geos_version_string, geos_version, \

      File "C:\Users\travis\AppData\Local\Temp\pip-install-a6csizkd\shapely\shapely\_buildcfg.py", line 205, in <module>

        lgeos = CDLL("geos_c.dll")

      File "C:\tools\miniconda3\envs\test\lib\ctypes\__init__.py", line 364, in __init__

        self._handle = _dlopen(self._name, mode)

    OSError: [WinError 126] The specified module could not be found

    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by sgillies** [comment]
@bsipocz thanks for the report! We're having some issues with our AppVeyor build and don't have Windows wheels uploaded yet. But also: if you're conda users, go ahead and grab Shapely from conda-forge, pip installing Shapely into a conda environment is not the right way to install.

**Comment by sgillies** [comment]
Windows wheels are on PyPI now.
